// Package action_kit_api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package action_kit_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ActionDescriptionAdditionalFlags.
const (
	DISABLEHEARTBEAT ActionDescriptionAdditionalFlags = "DISABLE_HEARTBEAT"
)

// Defines values for ActionHintType.
const (
	HintInfo    ActionHintType = "hint_info"
	HintWarning ActionHintType = "hint_warning"
)

// Defines values for ActionKind.
const (
	Attack   ActionKind = "attack"
	Check    ActionKind = "check"
	LoadTest ActionKind = "load_test"
	Other    ActionKind = "other"
)

// Defines values for ActionKitErrorStatus.
const (
	Errored ActionKitErrorStatus = "errored"
	Failed  ActionKitErrorStatus = "failed"
)

// Defines values for ActionParameterType.
const (
	ActionParameterTypeBitrate         ActionParameterType = "bitrate"
	ActionParameterTypeBoolean         ActionParameterType = "boolean"
	ActionParameterTypeDuration        ActionParameterType = "duration"
	ActionParameterTypeFile            ActionParameterType = "file"
	ActionParameterTypeHeader          ActionParameterType = "header"
	ActionParameterTypeInteger         ActionParameterType = "integer"
	ActionParameterTypeKeyValue        ActionParameterType = "key_value"
	ActionParameterTypePercentage      ActionParameterType = "percentage"
	ActionParameterTypeRegex           ActionParameterType = "regex"
	ActionParameterTypeSeparator       ActionParameterType = "separator"
	ActionParameterTypeStressngWorkers ActionParameterType = "stressng-workers"
	ActionParameterTypeString          ActionParameterType = "string"
	ActionParameterTypeString1         ActionParameterType = "string[]"
	ActionParameterTypeStringArray     ActionParameterType = "string_array"
	ActionParameterTypeTargetSelection ActionParameterType = "target-selection"
	ActionParameterTypeTextarea        ActionParameterType = "textarea"
	ActionParameterTypeUrl             ActionParameterType = "url"
)

// Defines values for DefaultBlastRadiusMode.
const (
	DefaultBlastRadiusModeMaximum    DefaultBlastRadiusMode = "maximum"
	DefaultBlastRadiusModePercentage DefaultBlastRadiusMode = "percentage"
)

// Defines values for DurationUnit.
const (
	DurationUnitDays         DurationUnit = "days"
	DurationUnitHours        DurationUnit = "hours"
	DurationUnitMilliseconds DurationUnit = "milliseconds"
	DurationUnitMinutes      DurationUnit = "minutes"
	DurationUnitSeconds      DurationUnit = "seconds"
)

// Defines values for ExecutionCommandAddValueToListPropertyType.
const (
	AddValueToListProperty ExecutionCommandAddValueToListPropertyType = "add_value_to_list_property"
)

// Defines values for ExecutionCommandDeletePropertyValueType.
const (
	DeletePropertyValue ExecutionCommandDeletePropertyValueType = "delete_property_value"
)

// Defines values for ExecutionCommandSetPropertyValueType.
const (
	SetPropertyValue ExecutionCommandSetPropertyValueType = "set_property_value"
)

// Defines values for LineChartWidgetType.
const (
	ComSteadybitWidgetLineChart LineChartWidgetType = "com.steadybit.widget.line_chart"
)

// Defines values for LineChartWidgetGroupMatcherFallbackType.
const (
	ComSteadybitWidgetLineChartGroupMatcherFallback LineChartWidgetGroupMatcherFallbackType = "com.steadybit.widget.line_chart.group_matcher_fallback"
)

// Defines values for LineChartWidgetGroupMatcherKeyEqualsValueType.
const (
	ComSteadybitWidgetLineChartGroupMatcherKeyEqualsValue LineChartWidgetGroupMatcherKeyEqualsValueType = "com.steadybit.widget.line_chart.group_matcher_key_equals_value"
)

// Defines values for LineChartWidgetGroupMatcherNotEmptyType.
const (
	ComSteadybitWidgetLineChartGroupMatcherNotEmpty LineChartWidgetGroupMatcherNotEmptyType = "com.steadybit.widget.line_chart.group_matcher_not_empty"
)

// Defines values for LineChartWidgetIdentityConfigMode.
const (
	ComSteadybitWidgetLineChartIdentityModeSelect         LineChartWidgetIdentityConfigMode = "com.steadybit.widget.line_chart.identity_mode.select"
	ComSteadybitWidgetLineChartIdentityModeWidgetPerValue LineChartWidgetIdentityConfigMode = "com.steadybit.widget.line_chart.identity_mode.widget-per-value"
)

// Defines values for LogWidgetType.
const (
	ComSteadybitWidgetLog LogWidgetType = "com.steadybit.widget.log"
)

// Defines values for MarkdownWidgetType.
const (
	ComSteadybitWidgetMarkdown MarkdownWidgetType = "com.steadybit.widget.markdown"
)

// Defines values for MessageLevel.
const (
	Debug MessageLevel = "debug"
	Error MessageLevel = "error"
	Info  MessageLevel = "info"
	Warn  MessageLevel = "warn"
)

// Defines values for MutatingHttpMethod.
const (
	DELETE MutatingHttpMethod = "DELETE"
	POST   MutatingHttpMethod = "POST"
	PUT    MutatingHttpMethod = "PUT"
)

// Defines values for PredefinedWidgetType.
const (
	ComSteadybitWidgetPredefined PredefinedWidgetType = "com.steadybit.widget.predefined"
)

// Defines values for ReadHttpMethod.
const (
	GET ReadHttpMethod = "GET"
)

// Defines values for StateOverTimeWidgetType.
const (
	ComSteadybitWidgetStateOverTime StateOverTimeWidgetType = "com.steadybit.widget.state_over_time"
)

// Defines values for TargetSelectionMissingQuerySelection.
const (
	MissingQuerySelectionIncludeAll  TargetSelectionMissingQuerySelection = "include_all"
	MissingQuerySelectionIncludeNone TargetSelectionMissingQuerySelection = "include_none"
)

// Defines values for TargetSelectionQuantityRestriction.
const (
	QuantityRestrictionAll        TargetSelectionQuantityRestriction = "all"
	QuantityRestrictionExactlyOne TargetSelectionQuantityRestriction = "exactly_one"
	QuantityRestrictionNone       TargetSelectionQuantityRestriction = "none"
)

// Defines values for TimeControl.
const (
	TimeControlExternal      TimeControl = "external"
	TimeControlInstantaneous TimeControl = "instantaneous"
	TimeControlInternal      TimeControl = "internal"
)

// Defines values for TimestampSource.
const (
	TimestampSourceExtension TimestampSource = "extension"
	TimestampSourceExternal  TimestampSource = "external"
)

// ActionDescription Provides details about a possible action, e.g., what configuration options it has, how to present it to end-users and how to trigger the action.
type ActionDescription struct {
	// AdditionalFlags Additional flags that are used to configure the action for specific cases:
	//   * `DISABLE_HEARTBEAT` - Disable the heartbeat between agent and platform for this action during execution
	AdditionalFlags *[]ActionDescriptionAdditionalFlags `json:"additionalFlags,omitempty"`

	// Category Used for categorization of the action within user interfaces. This is optional and mostly used as sub-category if certain actions should be grouped together.
	Category *string `json:"category,omitempty"`

	// Description Description for end-users to help them understand what the action is doing.
	Description string `json:"description"`

	// Hint Hints are used to provide additional information to the user. They are rendered in the ui when the user is configuring the action.
	Hint *ActionHint `json:"hint,omitempty"`

	// Icon An icon that is used to identify your action in the ui. Needs to be a data-uri containing an image.
	Icon *string `json:"icon,omitempty"`

	// Id A technical ID that is used to uniquely identify this type of action. You will typically want to use something like `org.example.my-fancy-attack`.
	Id string `json:"id"`

	// Kind Describes what kind of action this is. This is used to help users understand and classify the various runnable actions that are part of an experiment.
	Kind ActionKind `json:"kind"`

	// Label A human-readable label for the action.
	Label   string                `json:"label"`
	Metrics *MetricsConfiguration `json:"metrics,omitempty"`

	// Parameters Parameters that are used to configure the action. These parameters will be rendered in the ui and will be validated.
	Parameters []ActionParameter `json:"parameters"`

	// Prepare HTTP endpoint which the Steadybit platform/agent could communicate with.
	Prepare MutatingEndpointReference `json:"prepare"`

	// Start HTTP endpoint which the Steadybit platform/agent could communicate with.
	Start MutatingEndpointReference `json:"start"`

	// Status HTTP endpoint which the Steadybit platform/agent could communicate with.
	Status *MutatingEndpointReferenceWithCallInterval `json:"status,omitempty"`

	// Stop HTTP endpoint which the Steadybit platform/agent could communicate with.
	Stop *MutatingEndpointReference `json:"stop,omitempty"`

	// TargetSelection Used to specify various aspects of the target selection. If the action don't need a target selection, this field can be omitted.
	TargetSelection *TargetSelection `json:"targetSelection,omitempty"`
	// Deprecated: Use `TargetSelection.selectionTemplates` instead.
	TargetSelectionTemplates *TargetSelectionTemplates `json:"targetSelectionTemplates,omitempty"`
	// Deprecated: Use `TargetSelection.targetType` instead.
	TargetType *string `json:"targetType,omitempty"`

	// Technology Used for categorization of the action within user interfaces. In most cases, this will be the technology that the extension is about to handle, for example `AWS`, `Kubernetes` or `Host` or any custom technology you are writing an extension for.
	Technology *string `json:"technology,omitempty"`

	// TimeControl Actions can either be an instantaneous event, e.g., the restart of a host, or an activity spanning over an unspecified duration. For those actions having a duration, we differentiate between internally, e.g., waiting for a deployment to finish, and externally, e.g., waiting for a user-specified time to pass, controlled durations.
	TimeControl TimeControl `json:"timeControl"`

	// Version The version of the action. Remember to increase the value everytime you update the definitions. The platform will ignore any definition changes with the same action version. We do recommend usage of semver strings.
	Version string `json:"version"`

	// Widgets A list of widgets that can be rendered in the experiment result view after an experiment has finished. Any of
	//   - `action_kit_api.StateOverTimeWidget`
	//   - `action_kit_api.LogWidget`
	//   - `action_kit_api.MarkdownWidget`
	//   - `action_kit_api.PredefinedWidget`
	//   - `action_kit_api.LineChartWidget`
	Widgets *Widgets `json:"widgets,omitempty"`
}

// ActionDescriptionAdditionalFlags defines model for ActionDescription.AdditionalFlags.
type ActionDescriptionAdditionalFlags string

// ActionHint Hints are used to provide additional information to the user. They are rendered in the ui when the user is configuring the action.
type ActionHint struct {
	// Content The actual hint text (can contain markdown). Will be displayed in the product UI when configuring the action.
	Content string `json:"content"`

	// Type Will be used in the product UI to display the hint in a different color and with a different icon.
	Type ActionHintType `json:"type"`
}

// ActionHintType Will be used in the product UI to display the hint in a different color and with a different icon.
type ActionHintType string

// ActionKind Describes what kind of action this is. This is used to help users understand and classify the various runnable actions that are part of an experiment.
type ActionKind string

// ActionKitError An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
type ActionKitError struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status * failed - The action has detected some failures, for example a failing test which has been implemented by the action. The action will be stopped, if this status is returned by the status endpoint. * errored - There was a technical error while executing the action. Will be marked as red in the platform. The action will be stopped, if this status is returned by the status endpoint.
	Status *ActionKitErrorStatus `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type *string `json:"type,omitempty"`
}

// ActionKitErrorStatus * failed - The action has detected some failures, for example a failing test which has been implemented by the action. The action will be stopped, if this status is returned by the status endpoint. * errored - There was a technical error while executing the action. Will be marked as red in the platform. The action will be stopped, if this status is returned by the status endpoint.
type ActionKitErrorStatus string

// ActionList Lists all actions that the platform/agent could execute.
type ActionList struct {
	Actions []DescribingEndpointReference `json:"actions"`
}

// ActionParameter defines model for ActionParameter.
type ActionParameter struct {
	// AcceptedFileTypes Unique file type specifiers describing what type of files are accepted for parameters of type 'file'.
	AcceptedFileTypes *[]string `json:"acceptedFileTypes,omitempty"`

	// Advanced Whether this parameter should be placed under the expandable advanced section within the user interface.
	Advanced *bool `json:"advanced,omitempty"`

	// DefaultValue A default value for this parameter. This value will be used if the user does not specify a value for this parameter.
	DefaultValue *string `json:"defaultValue,omitempty"`

	// Deprecated Whether or not this parameter is deprecated. Deprecated parameters will be hidden from the user interface when configuring a new step. Existing steps will still be able to use deprecated parameters. A deprecated parameter should not be required nor have a defaultValue.
	Deprecated *bool `json:"deprecated,omitempty"`

	// DeprecationMessage A message that will be shown to the user when they are configuring the action. This could for example include a hint to use a replacement.
	DeprecationMessage *string `json:"deprecationMessage,omitempty"`

	// Description Description for end-users to help them understand the action parameter.
	Description *string `json:"description,omitempty"`

	// DurationUnits DurationUnits Specifies the units that are accepted for parameters of type 'duration'. Defaults are 'milliseconds', 'seconds', 'minutes'.
	DurationUnits *[]DurationUnit `json:"durationUnits,omitempty"`

	// Hint Hints are used to provide additional information to the user. They are rendered in the ui when the user is configuring the action.
	Hint *ActionHint `json:"hint,omitempty"`

	// Label A human-readable label for the action parameter.
	Label string `json:"label"`

	// MaxValue The minimum value for this parameter. Only applicable for parameters of type `integer`, `percentage`, and `duration`. In the case of `duration`, the value is in milliseconds.
	MaxValue *int `json:"maxValue,omitempty"`

	// MinValue The minimum value for this parameter. Only applicable for parameters of type `integer`, `percentage`, and `duration`. In the case of `duration`, the value is in milliseconds.
	MinValue *int `json:"minValue,omitempty"`

	// Name The key under which the action parameter is stored. This key can then be found within the prepare request's config field.
	Name string `json:"name"`

	// Options Optional options for the `string`, `string[]` and `string_array` parameter types. Which result in suggestions for end-users. Any of:
	//  - `action_kit_api.ExplicitParameterOption`
	//  - `action_kit_api.ParameterOptionsFromTargetAttribute`
	Options *[]ParameterOption `json:"options,omitempty"`

	// OptionsOnly Define if for a type = 'string' with options, if only the options should be allowed or also free text. Default is true.
	OptionsOnly *bool `json:"optionsOnly,omitempty"`
	// Deprecated: The position in the list will determine the order.
	Order *int `json:"order,omitempty"`

	// Required Whether or not end-users need to specify a value for this parameter.
	Required *bool `json:"required,omitempty"`

	// Type What kind of value this parameter is capturing. The type selection influences the `config` passed as part of the `PrepareRequest`. It also results in improved user-interface elements.
	Type ActionParameterType `json:"type"`
}

// ActionParameterType What kind of value this parameter is capturing. The type selection influences the `config` passed as part of the `PrepareRequest`. It also results in improved user-interface elements.
type ActionParameterType string

// ActionState Any kind of action specific state that will be passed to the next endpoints.
type ActionState map[string]interface{}

// Artifact Actions may choose to provide artifacts (arbitrary files) that are later accessible by users when inspecting experiment execution details. This comes in handy to expose load test reports and similar data.
type Artifact struct {
	// Data base64 encoded data
	Data string `json:"data"`

	// Label Human-readable label for the artifact. We recommend to include file extensions within the label for a better user-experience when downloading these artifacts, e.g., load_test_result.tar.gz.
	Label string `json:"label"`
}

// Artifacts defines model for Artifacts.
type Artifacts = []Artifact

// DefaultBlastRadius The default blast radius configuration for the action. (Default: 100 percent)
type DefaultBlastRadius struct {
	// Mode The mode of the randomizer. If set to `percentage`, the platform will pick n percent of the selected targets. If set to `maximum`, the randomizer pick n targets.
	Mode DefaultBlastRadiusMode `json:"mode"`

	// Value If the mode is set to `percentage`, the value is the percentage of the selected targets. If the mode is set to `maximum`, the value is the number of targets.
	Value int `json:"value"`
}

// DefaultBlastRadiusMode The mode of the randomizer. If set to `percentage`, the platform will pick n percent of the selected targets. If set to `maximum`, the randomizer pick n targets.
type DefaultBlastRadiusMode string

// DescribingEndpointReference HTTP endpoint which the Steadybit platform/agent could communicate with.
type DescribingEndpointReference struct {
	Method ReadHttpMethod `json:"method"`

	// Path Absolute path of the HTTP endpoint.
	Path string `json:"path"`
}

// DurationUnit Specifies the units that are accepted for parameters of type 'duration'. Defaults are 'milliseconds', 'seconds', 'minutes'.
type DurationUnit string

// ExecutionCommand A command that can be used to modify the experiment execution (e.g. properties) Any of
//   - `action_kit_api.ExecutionCommandSetPropertyValue`
//   - `action_kit_api.ExecutionCommandDeletePropertyValue`
//   - `action_kit_api.ExecutionCommandAddValueToListProperty`
type ExecutionCommand struct {
	union json.RawMessage
}

// ExecutionCommandAddValueToListProperty Adds a value to a list property within the experiment execution's properties.
type ExecutionCommandAddValueToListProperty struct {
	// PropertyKey The key of the property.
	PropertyKey string `json:"propertyKey"`

	// Type The type of the command. Needs to be set to `action_kit_api.AddValueToListProperty`.
	Type ExecutionCommandAddValueToListPropertyType `json:"type"`

	// Value The value to add.
	Value map[string]interface{} `json:"value"`
}

// ExecutionCommandAddValueToListPropertyType The type of the command. Needs to be set to `action_kit_api.AddValueToListProperty`.
type ExecutionCommandAddValueToListPropertyType string

// ExecutionCommandDeletePropertyValue Delete the value of a property within the experiment execution's properties.
type ExecutionCommandDeletePropertyValue struct {
	// PropertyKey The key of the property.
	PropertyKey string `json:"propertyKey"`

	// Type The type of the command. Needs to be set to `action_kit_api.DeletePropertyValue`.
	Type ExecutionCommandDeletePropertyValueType `json:"type"`
}

// ExecutionCommandDeletePropertyValueType The type of the command. Needs to be set to `action_kit_api.DeletePropertyValue`.
type ExecutionCommandDeletePropertyValueType string

// ExecutionCommandSetPropertyValue Set the value of a property within the experiment execution's properties.
type ExecutionCommandSetPropertyValue struct {
	// PropertyKey The key of the property.
	PropertyKey string `json:"propertyKey"`

	// Type The type of the command. Needs to be set to `action_kit_api.SetPropertyValue`.
	Type ExecutionCommandSetPropertyValueType `json:"type"`

	// Value The value to set.
	Value map[string]interface{} `json:"value"`
}

// ExecutionCommandSetPropertyValueType The type of the command. Needs to be set to `action_kit_api.SetPropertyValue`.
type ExecutionCommandSetPropertyValueType string

// ExecutionCommands A list of commands that can be used to modify the experiment execution (e.g. properties) Any of
//   - `action_kit_api.ExecutionCommandSetPropertyValue`
//   - `action_kit_api.ExecutionCommandDeletePropertyValue`
//   - `action_kit_api.ExecutionCommandAddValueToListProperty`
type ExecutionCommands = []ExecutionCommand

// ExecutionContext The execution context contains information about the current execution of the action.
type ExecutionContext struct {
	// AgentAwsAccountId The AWS account ID of the agent that is executing the action. This is only set when the action is executed on an AWS account
	AgentAwsAccountId *string `json:"agentAwsAccountId,omitempty"`

	// AgentPid The process ID of the agent that is executing the action.
	AgentPid *int `json:"agentPid,omitempty"`

	// ExecutionId The execution ID of the current execution.
	ExecutionId *int `json:"executionId,omitempty"`

	// ExecutionUri The execution URI of the current execution.
	ExecutionUri *string `json:"executionUri,omitempty"`

	// ExperimentKey The experiment key of the experiment that is currently being executed.
	ExperimentKey *string `json:"experimentKey,omitempty"`

	// ExperimentUri The experiment URI of the experiment that is currently being executed.
	ExperimentUri *string `json:"experimentUri,omitempty"`

	// RestrictedEndpoints Endpoints that are used by the agent (e.g to communicate with extensions and platform). These Connections shall not be affected by actions / attacks.
	RestrictedEndpoints *[]RestrictedEndpoint `json:"restrictedEndpoints,omitempty"`
}

// ExplicitParameterOption You can use an explicit/fixed parameter option for a known / finite set of options that never change.
type ExplicitParameterOption struct {
	// Label A human-readable label describing this option.
	Label string `json:"label"`

	// Value The technical value which will be passed to the action as part of the `config` object.
	Value string `json:"value"`
}

// LineChartWidget A widget that shows a line chart.
type LineChartWidget struct {
	// Grouping Optional configuration to group some data points in the line chart. Groups can be colored and a summary can be shown in an Pie chart next to the line chart.
	Grouping *LineChartWidgetGroupingConfig `json:"grouping,omitempty"`
	Identity LineChartWidgetIdentityConfig  `json:"identity"`

	// Title The title of the widget. This will be displayed in the widget header.
	Title   string                        `json:"title"`
	Tooltip *LineChartWidgetTooltipConfig `json:"tooltip,omitempty"`

	// Type The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetLineChart`.
	Type LineChartWidgetType `json:"type"`
}

// LineChartWidgetType The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetLineChart`.
type LineChartWidgetType string

// LineChartWidgetGroup A group of data points in the line chart.
type LineChartWidgetGroup struct {
	// Color The color of the group. This will be used to color the matching data points in the line chart.
	Color string `json:"color"`

	// Matcher The matcher that should be used to match the data points that should be part of this group. Any of
	//  - `action_kit_api.LineChartWidgetGroupMatcherFallback`
	//  - `action_kit_api.LineChartWidgetGroupMatcherKeyEqualsValue`
	//  - `action_kit_api.LineChartWidgetGroupMatcherNotEmpty`
	Matcher LineChartWidgetGroupMatcher `json:"matcher"`

	// Title The title of the group. This will be displayed in the tooltip and the pie chart summary of the widget
	Title string `json:"title"`
}

// LineChartWidgetGroupMatcherFallback A fallback matcher that will match all data points that are not matched by any other group.
type LineChartWidgetGroupMatcherFallback struct {
	// Type The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetLineChartGroupMatcherFallback`.
	Type LineChartWidgetGroupMatcherFallbackType `json:"type"`
}

// LineChartWidgetGroupMatcherFallbackType The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetLineChartGroupMatcherFallback`.
type LineChartWidgetGroupMatcherFallbackType string

// LineChartWidgetGroupMatcherKeyEqualsValue A matcher that will match all data points where the value of the specified key equals the specified value.
type LineChartWidgetGroupMatcherKeyEqualsValue struct {
	Key string `json:"key"`

	// Type The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetLineChartGroupMatcherKeyEqualsValue`.
	Type  LineChartWidgetGroupMatcherKeyEqualsValueType `json:"type"`
	Value string                                        `json:"value"`
}

// LineChartWidgetGroupMatcherKeyEqualsValueType The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetLineChartGroupMatcherKeyEqualsValue`.
type LineChartWidgetGroupMatcherKeyEqualsValueType string

// LineChartWidgetGroupMatcherNotEmpty A matcher that will match all data points where the value of the specified key is not empty.
type LineChartWidgetGroupMatcherNotEmpty struct {
	Key string `json:"key"`

	// Type The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetLineChartGroupMatcherNotEmpty`.
	Type LineChartWidgetGroupMatcherNotEmptyType `json:"type"`
}

// LineChartWidgetGroupMatcherNotEmptyType The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetLineChartGroupMatcherNotEmpty`.
type LineChartWidgetGroupMatcherNotEmptyType string

// LineChartWidgetGroupingConfig Optional configuration to group some data points in the line chart. Groups can be colored and a summary can be shown in an Pie chart next to the line chart.
type LineChartWidgetGroupingConfig struct {
	// Groups A list of groups that should be displayed in the line chart. Each group can be colored and a matcher can be defined to match the data points that should be part of this group.
	Groups []LineChartWidgetGroup `json:"groups"`

	// ShowSummary If set to `true`, a pie chart will be shown next to the line chart. The pie chart will show the summary of the groups and can be used to filter data points in the line chart.
	ShowSummary *bool `json:"showSummary,omitempty"`
}

// LineChartWidgetIdentityConfig defines model for LineChartWidgetIdentityConfig.
type LineChartWidgetIdentityConfig struct {
	// From The name of a metric field containing a unique identifier per desired line chart within the UI.
	From string `json:"from"`

	// MetricName The name of the metrics that should be considered for this line chart.
	MetricName string `json:"metricName"`

	// Mode If there are multiple values by evaluating `from`, how should the widgets be rendered?
	//  - `com.steadybit.widget.line_chart.identity_mode.select` - A single widget is rendered and the user can select the value that should be displayed in the widget.
	//  - `com.steadybit.widget.line_chart.identity_mode.widget-per-value` - A separate widget is rendered per given value.
	Mode LineChartWidgetIdentityConfigMode `json:"mode"`
}

// LineChartWidgetIdentityConfigMode If there are multiple values by evaluating `from`, how should the widgets be rendered?
//   - `com.steadybit.widget.line_chart.identity_mode.select` - A single widget is rendered and the user can select the value that should be displayed in the widget.
//   - `com.steadybit.widget.line_chart.identity_mode.widget-per-value` - A separate widget is rendered per given value.
type LineChartWidgetIdentityConfigMode string

// LineChartWidgetTooltipConfig defines model for LineChartWidgetTooltipConfig.
type LineChartWidgetTooltipConfig struct {
	// AdditionalContent Additional content that should be displayed in the tooltip. This can be used to show additional information about the data points in the line chart.
	AdditionalContent []LineChartWidgetTooltipContent `json:"additionalContent"`

	// MetricValueTitle Optional title of the metric value that should be displayed in the tooltip.
	MetricValueTitle *string `json:"metricValueTitle,omitempty"`

	// MetricValueUnit Optional unit of the metric value that should be displayed in the tooltip.
	MetricValueUnit *string `json:"metricValueUnit,omitempty"`
}

// LineChartWidgetTooltipContent defines model for LineChartWidgetTooltipContent.
type LineChartWidgetTooltipContent struct {
	// From The name of a metric field containing the value for this additional content.
	From string `json:"from"`

	// Title The title of the additional content. This will be displayed as caption for the value in the tooltip.
	Title string `json:"title"`

	// Unit Optional unit which should be added next to the value in the tooltip.
	Unit *string `json:"unit,omitempty"`
}

// LogWidget A widget that shows log messages.
type LogWidget struct {
	// LogType The type of messages that should be displayed in the widget. Needs to match `type` in `action_kit_api.Message`.
	LogType string `json:"logType"`

	// Title The title of the widget. This will be displayed in the widget header.
	Title string `json:"title"`

	// Type The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetLog`.
	Type LogWidgetType `json:"type"`
}

// LogWidgetType The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetLog`.
type LogWidgetType string

// MarkdownWidget A widget that renders Markdown content.
type MarkdownWidget struct {
	// Append If set to `true`, the widget will append the content to the existing content of previous endpoint calls. For example, you can return some headings in the `start` call, append some progress information in the `status` calls and add a summary in the `stop` call. If set to `false`, the widget will only show the last submitted content batch, grouped by `timestamp`. Older content will be displayed, when clicking on the timeline in the run view. To improve the performance, you should only return messages if the content has changed compared to the previous batch.
	Append bool `json:"append"`

	// MessageType The type of messages that should be displayed in the widget. Needs to match `type` in `action_kit_api.Message`.
	MessageType string `json:"messageType"`

	// Title The title of the widget. This will be displayed in the widget header.
	Title string `json:"title"`

	// Type The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetMarkdown`.
	Type MarkdownWidgetType `json:"type"`
}

// MarkdownWidgetType The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetMarkdown`.
type MarkdownWidgetType string

// Message Log-message that will be passed to the platform (default agent log).
type Message struct {
	// Fields Any kind of action specific fields that will be rendered in the platform tooltip of LogWidget
	Fields    *MessageFields `json:"fields,omitempty"`
	Level     *MessageLevel  `json:"level,omitempty"`
	Message   string         `json:"message"`
	Timestamp *time.Time     `json:"timestamp,omitempty"`

	// TimestampSource Source of the timestamp. This is useful when the timestamp is retrieved from some other system. If not specified or equals `extension` the agent will adjust the timestamp with an offset calculated from the response date header and the platform's current time.
	TimestampSource *TimestampSource `json:"timestampSource,omitempty"`
	Type            *string          `json:"type,omitempty"`
}

// MessageLevel defines model for Message.Level.
type MessageLevel string

// MessageFields Any kind of action specific fields that will be rendered in the platform tooltip of LogWidget
type MessageFields map[string]string

// Messages Log-messages that will be passed to the platform (default agent log).
type Messages = []Message

// Metric Metrics can be exposed by actions. These metrics can then be leveraged by end-users to inspect system behavior and to optionally abort experiment execution when certain metrics are observed, i.e., metrics can act as (steady state) checks.
type Metric struct {
	// Metric Key/value pairs describing the metric. This type is modeled after Prometheus' data model, i.e., metric labels. You may encode the metric name as `__name__` similar to how Prometheus does it.
	Metric map[string]string `json:"metric"`

	// Name Metric name. You can alternatively encode the metric name as `__name__` within the metric property.
	Name *string `json:"name,omitempty"`

	// Timestamp Timestamp describing at which moment the value was observed.
	Timestamp time.Time `json:"timestamp"`

	// TimestampSource Source of the timestamp. This is useful when the timestamp is retrieved from some other system. If not specified or equals `extension` the agent will adjust the timestamp with an offset calculated from the response date header and the platform's current time.
	TimestampSource *TimestampSource `json:"timestampSource,omitempty"`
	Value           float64          `json:"value"`
}

// Metrics defines model for Metrics.
type Metrics = []Metric

// MetricsConfiguration defines model for MetricsConfiguration.
type MetricsConfiguration struct {
	Query *MetricsQueryConfiguration `json:"query,omitempty"`
}

// MetricsQueryConfiguration defines model for MetricsQueryConfiguration.
type MetricsQueryConfiguration struct {
	// Endpoint HTTP endpoint which the Steadybit platform/agent could communicate with.
	Endpoint   MutatingEndpointReferenceWithCallInterval `json:"endpoint"`
	Parameters []ActionParameter                         `json:"parameters"`
}

// MutatingEndpointReference HTTP endpoint which the Steadybit platform/agent could communicate with.
type MutatingEndpointReference struct {
	Method MutatingHttpMethod `json:"method"`

	// Path Absolute path of the HTTP endpoint.
	Path string `json:"path"`
}

// MutatingEndpointReferenceWithCallInterval defines model for MutatingEndpointReferenceWithCallInterval.
type MutatingEndpointReferenceWithCallInterval struct {
	// CallInterval At what frequency should the state endpoint be called? Takes durations in the format of `100ms` or `10s`.
	CallInterval *string            `json:"callInterval,omitempty"`
	Method       MutatingHttpMethod `json:"method"`

	// Path Absolute path of the HTTP endpoint.
	Path string `json:"path"`
}

// MutatingHttpMethod defines model for MutatingHttpMethod.
type MutatingHttpMethod string

// ParameterOptionsFromTargetAttribute A meta option that represents all target attribute values for the key defined through the attribute field.
type ParameterOptionsFromTargetAttribute struct {
	// Attribute Target attribute key from which the possible parameter options are gathered.
	Attribute string `json:"attribute"`
}

// PredefinedWidget The platform contains a set of hand crafted predefined widgets. This widget type allows to use one of them.
type PredefinedWidget struct {
	PredefinedWidgetId string `json:"predefinedWidgetId"`

	// Type The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetPredefined`.
	Type PredefinedWidgetType `json:"type"`
}

// PredefinedWidgetType The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetPredefined`.
type PredefinedWidgetType string

// PrepareResult defines model for PrepareResult.
type PrepareResult struct {
	Artifacts *Artifacts `json:"artifacts,omitempty"`

	// Commands A list of commands that can be used to modify the experiment execution (e.g. properties) Any of
	//   - `action_kit_api.ExecutionCommandSetPropertyValue`
	//   - `action_kit_api.ExecutionCommandDeletePropertyValue`
	//   - `action_kit_api.ExecutionCommandAddValueToListProperty`
	Commands *ExecutionCommands `json:"commands,omitempty"`

	// Error An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
	Error *ActionKitError `json:"error,omitempty"`

	// Messages Log-messages that will be passed to the platform (default agent log).
	Messages *Messages `json:"messages,omitempty"`
	Metrics  *Metrics  `json:"metrics,omitempty"`

	// State Any kind of action specific state that will be passed to the next endpoints.
	State ActionState `json:"state"`
}

// QueryMetricsResult defines model for QueryMetricsResult.
type QueryMetricsResult struct {
	Artifacts *Artifacts `json:"artifacts,omitempty"`

	// Messages Log-messages that will be passed to the platform (default agent log).
	Messages *Messages `json:"messages,omitempty"`
	Metrics  *Metrics  `json:"metrics,omitempty"`
}

// ReadHttpMethod defines model for ReadHttpMethod.
type ReadHttpMethod string

// RestrictedEndpoint defines model for RestrictedEndpoint.
type RestrictedEndpoint struct {
	// Cidr A CIDR that is used to restrict the target selection to a specific network.
	Cidr string `json:"cidr"`

	// Name The name of the protected Endpoint. For reference/debugging purposes only.
	Name string `json:"name"`

	// PortMax The maximum port number that is allowed to be used for the Endpoint.
	PortMax int `json:"portMax"`

	// PortMin The minimum port number that is allowed to be used for the Endpoint.
	PortMin int `json:"portMin"`

	// Url The URL of the protected Endpoint.
	Url string `json:"url"`
}

// StartResult defines model for StartResult.
type StartResult struct {
	Artifacts *Artifacts `json:"artifacts,omitempty"`

	// Commands A list of commands that can be used to modify the experiment execution (e.g. properties) Any of
	//   - `action_kit_api.ExecutionCommandSetPropertyValue`
	//   - `action_kit_api.ExecutionCommandDeletePropertyValue`
	//   - `action_kit_api.ExecutionCommandAddValueToListProperty`
	Commands *ExecutionCommands `json:"commands,omitempty"`

	// Error An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
	Error *ActionKitError `json:"error,omitempty"`

	// Messages Log-messages that will be passed to the platform (default agent log).
	Messages *Messages `json:"messages,omitempty"`
	Metrics  *Metrics  `json:"metrics,omitempty"`

	// State Any kind of action specific state that will be passed to the next endpoints.
	State *ActionState `json:"state,omitempty"`
}

// StateOverTimeWidget A widget that shows a state of over time.
type StateOverTimeWidget struct {
	Identity StateOverTimeWidgetIdentityConfig `json:"identity"`
	Label    StateOverTimeWidgetLabelConfig    `json:"label"`
	State    StateOverTimeWidgetStateConfig    `json:"state"`

	// Title The title of the widget. This will be displayed in the widget header.
	Title   string                           `json:"title"`
	Tooltip StateOverTimeWidgetTooltipConfig `json:"tooltip"`

	// Type The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetStateOverTime`.
	Type  StateOverTimeWidgetType         `json:"type"`
	Url   *StateOverTimeWidgetUrlConfig   `json:"url,omitempty"`
	Value *StateOverTimeWidgetValueConfig `json:"value,omitempty"`
}

// StateOverTimeWidgetType The type of the widget. Needs to be set to `action_kit_api.ComSteadybitWidgetStateOverTime`.
type StateOverTimeWidgetType string

// StateOverTimeWidgetIdentityConfig defines model for StateOverTimeWidgetIdentityConfig.
type StateOverTimeWidgetIdentityConfig struct {
	// From The name of a metric field containing a unique identifier per desired chart row within the UI.
	From string `json:"from"`
}

// StateOverTimeWidgetLabelConfig defines model for StateOverTimeWidgetLabelConfig.
type StateOverTimeWidgetLabelConfig struct {
	// From The name of a metric field containing a human-readable label per desired chart row within the UI.
	From string `json:"from"`
}

// StateOverTimeWidgetStateConfig defines model for StateOverTimeWidgetStateConfig.
type StateOverTimeWidgetStateConfig struct {
	// From The name of a metric field containing the current state at any time.
	From string `json:"from"`
}

// StateOverTimeWidgetTooltipConfig defines model for StateOverTimeWidgetTooltipConfig.
type StateOverTimeWidgetTooltipConfig struct {
	// From The name of a metric field containing the current tooltip at any time.
	From string `json:"from"`
}

// StateOverTimeWidgetUrlConfig defines model for StateOverTimeWidgetUrlConfig.
type StateOverTimeWidgetUrlConfig struct {
	// From The name of a metric field containing a URL. When available, it causes a chart segment to turn into a hyperlink.
	From *string `json:"from,omitempty"`
}

// StateOverTimeWidgetValueConfig defines model for StateOverTimeWidgetValueConfig.
type StateOverTimeWidgetValueConfig struct {
	// Hide Set to true to hide the metric value within the widget. This is useful when only the translated state information is relevant.
	Hide *bool `json:"hide,omitempty"`
}

// StatusResult defines model for StatusResult.
type StatusResult struct {
	Artifacts *Artifacts `json:"artifacts,omitempty"`

	// Commands A list of commands that can be used to modify the experiment execution (e.g. properties) Any of
	//   - `action_kit_api.ExecutionCommandSetPropertyValue`
	//   - `action_kit_api.ExecutionCommandDeletePropertyValue`
	//   - `action_kit_api.ExecutionCommandAddValueToListProperty`
	Commands *ExecutionCommands `json:"commands,omitempty"`

	// Completed the agent will continue to poll the status endpoint as long as completed is false and no error is set
	Completed bool `json:"completed"`

	// Error An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
	Error *ActionKitError `json:"error,omitempty"`

	// Messages Log-messages that will be passed to the platform (default agent log).
	Messages *Messages `json:"messages,omitempty"`
	Metrics  *Metrics  `json:"metrics,omitempty"`

	// State Any kind of action specific state that will be passed to the next endpoints.
	State *ActionState `json:"state,omitempty"`
}

// StopResult defines model for StopResult.
type StopResult struct {
	Artifacts *Artifacts `json:"artifacts,omitempty"`

	// Commands A list of commands that can be used to modify the experiment execution (e.g. properties) Any of
	//   - `action_kit_api.ExecutionCommandSetPropertyValue`
	//   - `action_kit_api.ExecutionCommandDeletePropertyValue`
	//   - `action_kit_api.ExecutionCommandAddValueToListProperty`
	Commands *ExecutionCommands `json:"commands,omitempty"`

	// Error An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
	Error *ActionKitError `json:"error,omitempty"`

	// Messages Log-messages that will be passed to the platform (default agent log).
	Messages *Messages `json:"messages,omitempty"`
	Metrics  *Metrics  `json:"metrics,omitempty"`
}

// Target The target on which to act on as identified by a discovery.
type Target struct {
	// Attributes These attributes include detailed information about the target provided through the discovery. These attributes are typically used as additional parameters within the action implementation.
	Attributes map[string][]string `json:"attributes"`
	Name       string              `json:"name"`
}

// TargetSelection Used to specify various aspects of the target selection. If the action don't need a target selection, this field can be omitted.
type TargetSelection struct {
	// DefaultBlastRadius The default blast radius configuration for the action. (Default: 100 percent)
	DefaultBlastRadius *DefaultBlastRadius `json:"defaultBlastRadius,omitempty"`

	// MissingQuerySelection The default selection of the targets in the UI if no query is provided by the user. * 'include_all' All targets will be selected by default * 'include_none' (default) No targets will be selected by default
	MissingQuerySelection *TargetSelectionMissingQuerySelection `json:"missingQuerySelection,omitempty"`

	// QuantityRestriction How many targets should be selected by the user. Values:
	//  * `exactly_one` - Exactly one target must be selected. The execution will fail if more than one target is selected.
	//  * `all` - All selected targets will be used. The ui will not show a percentage randomizer for the target selection.
	//  * `none` - Default. There are no restriction in place for the number of targets. The ui will show a percentage randomizer for the target selection.
	QuantityRestriction *TargetSelectionQuantityRestriction `json:"quantityRestriction,omitempty"`

	// SelectionTemplates Users that want to configure an action with a targetType need to define a target selection through the query UI or query language. Extensions can define selection templates to help users define such target selections.
	SelectionTemplates *TargetSelectionTemplates `json:"selectionTemplates,omitempty"`

	// TargetType What target type this action should be offered for. Matches the `id` field within `DescribeTargetTypeResponse` within DiscoveryKit.
	TargetType string `json:"targetType"`
}

// TargetSelectionMissingQuerySelection The default selection of the targets in the UI if no query is provided by the user. * 'include_all' All targets will be selected by default * 'include_none' (default) No targets will be selected by default
type TargetSelectionMissingQuerySelection string

// TargetSelectionQuantityRestriction How many targets should be selected by the user. Values:
//   - `exactly_one` - Exactly one target must be selected. The execution will fail if more than one target is selected.
//   - `all` - All selected targets will be used. The ui will not show a percentage randomizer for the target selection.
//   - `none` - Default. There are no restriction in place for the number of targets. The ui will show a percentage randomizer for the target selection.
type TargetSelectionQuantityRestriction string

// TargetSelectionTemplate defines model for TargetSelectionTemplate.
type TargetSelectionTemplate struct {
	// Description Longer target selection template description. For example, to explain the template's purpose.
	Description *string `json:"description,omitempty"`

	// Label Human-readable short label.
	Label string `json:"label"`

	// Query The target selection query is defined using Steadybit's query language. For example:
	//   aws.account="" AND aws.zone.id=""
	// For more information about the query language, please inspect Steadybit's documentation:
	//   https://docs.steadybit.com/use-steadybit/query-language
	Query string `json:"query"`
}

// TargetSelectionTemplates Users that want to configure an action with a targetType need to define a target selection through the query UI or query language. Extensions can define selection templates to help users define such target selections.
type TargetSelectionTemplates = []TargetSelectionTemplate

// TimeControl Actions can either be an instantaneous event, e.g., the restart of a host, or an activity spanning over an unspecified duration. For those actions having a duration, we differentiate between internally, e.g., waiting for a deployment to finish, and externally, e.g., waiting for a user-specified time to pass, controlled durations.
type TimeControl string

// TimestampSource Source of the timestamp. This is useful when the timestamp is retrieved from some other system. If not specified or equals `extension` the agent will adjust the timestamp with an offset calculated from the response date header and the platform's current time.
type TimestampSource string

// Widgets A list of widgets that can be rendered in the experiment result view after an experiment has finished. Any of
//   - `action_kit_api.StateOverTimeWidget`
//   - `action_kit_api.LogWidget`
//   - `action_kit_api.MarkdownWidget`
//   - `action_kit_api.PredefinedWidget`
//   - `action_kit_api.LineChartWidget`
type Widgets = []Widget

// ActionListResponse defines model for ActionListResponse.
type ActionListResponse struct {
	union json.RawMessage
}

// ActionStatusResponse defines model for ActionStatusResponse.
type ActionStatusResponse struct {
	union json.RawMessage
}

// DescribeActionResponse defines model for DescribeActionResponse.
type DescribeActionResponse struct {
	union json.RawMessage
}

// PrepareActionResponse defines model for PrepareActionResponse.
type PrepareActionResponse struct {
	union json.RawMessage
}

// QueryMetricsResponse defines model for QueryMetricsResponse.
type QueryMetricsResponse struct {
	union json.RawMessage
}

// StartActionResponse defines model for StartActionResponse.
type StartActionResponse struct {
	union json.RawMessage
}

// StopActionResponse defines model for StopActionResponse.
type StopActionResponse struct {
	union json.RawMessage
}

// ActionStatusRequestBody defines model for ActionStatusRequestBody.
type ActionStatusRequestBody struct {
	ExecutionId uuid.UUID `json:"executionId"`

	// State Any kind of action specific state that will be passed to the next endpoints.
	State ActionState `json:"state"`
}

// PrepareActionRequestBody defines model for PrepareActionRequestBody.
type PrepareActionRequestBody struct {
	// Config The action configuration. This contains the end-user configuration done for the action. Possible configuration parameters are defined through the action description.
	Config map[string]interface{} `json:"config"`

	// ExecutionContext The execution context contains information about the current execution of the action.
	ExecutionContext *ExecutionContext `json:"executionContext,omitempty"`
	ExecutionId      uuid.UUID         `json:"executionId"`

	// Target The target on which to act on as identified by a discovery.
	Target *Target `json:"target,omitempty"`
}

// QueryMetricsRequestBody defines model for QueryMetricsRequestBody.
type QueryMetricsRequestBody struct {
	// Config The metric query configuration. This contains the end-user configuration done for the action. Possible configuration parameters are defined through the action description.
	Config      map[string]interface{} `json:"config"`
	ExecutionId uuid.UUID              `json:"executionId"`

	// Target The target on which to act on as identified by a discovery.
	Target *Target `json:"target,omitempty"`

	// Timestamp For what timestamp the metric values should be retrieved.
	Timestamp time.Time `json:"timestamp"`
}

// StartActionRequestBody defines model for StartActionRequestBody.
type StartActionRequestBody struct {
	ExecutionId uuid.UUID `json:"executionId"`

	// State Any kind of action specific state that will be passed to the next endpoints.
	State ActionState `json:"state"`
}

// StopActionRequestBody defines model for StopActionRequestBody.
type StopActionRequestBody struct {
	ExecutionId uuid.UUID `json:"executionId"`

	// State Any kind of action specific state that will be passed to the next endpoints.
	State ActionState `json:"state"`
}

// AsExecutionCommandSetPropertyValue returns the union data inside the ExecutionCommand as a ExecutionCommandSetPropertyValue
func (t ExecutionCommand) AsExecutionCommandSetPropertyValue() (ExecutionCommandSetPropertyValue, error) {
	var body ExecutionCommandSetPropertyValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExecutionCommandSetPropertyValue overwrites any union data inside the ExecutionCommand as the provided ExecutionCommandSetPropertyValue
func (t *ExecutionCommand) FromExecutionCommandSetPropertyValue(v ExecutionCommandSetPropertyValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExecutionCommandSetPropertyValue performs a merge with any union data inside the ExecutionCommand, using the provided ExecutionCommandSetPropertyValue
func (t *ExecutionCommand) MergeExecutionCommandSetPropertyValue(v ExecutionCommandSetPropertyValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ExecutionCommand) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ExecutionCommand) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsActionList returns the union data inside the ActionListResponse as a ActionList
func (t ActionListResponse) AsActionList() (ActionList, error) {
	var body ActionList
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionList overwrites any union data inside the ActionListResponse as the provided ActionList
func (t *ActionListResponse) FromActionList(v ActionList) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionList performs a merge with any union data inside the ActionListResponse, using the provided ActionList
func (t *ActionListResponse) MergeActionList(v ActionList) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the ActionListResponse as a ActionKitError
func (t ActionListResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the ActionListResponse as the provided ActionKitError
func (t *ActionListResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the ActionListResponse, using the provided ActionKitError
func (t *ActionListResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ActionListResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ActionListResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStatusResult returns the union data inside the ActionStatusResponse as a StatusResult
func (t ActionStatusResponse) AsStatusResult() (StatusResult, error) {
	var body StatusResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStatusResult overwrites any union data inside the ActionStatusResponse as the provided StatusResult
func (t *ActionStatusResponse) FromStatusResult(v StatusResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStatusResult performs a merge with any union data inside the ActionStatusResponse, using the provided StatusResult
func (t *ActionStatusResponse) MergeStatusResult(v StatusResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the ActionStatusResponse as a ActionKitError
func (t ActionStatusResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the ActionStatusResponse as the provided ActionKitError
func (t *ActionStatusResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the ActionStatusResponse, using the provided ActionKitError
func (t *ActionStatusResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ActionStatusResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ActionStatusResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsActionDescription returns the union data inside the DescribeActionResponse as a ActionDescription
func (t DescribeActionResponse) AsActionDescription() (ActionDescription, error) {
	var body ActionDescription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionDescription overwrites any union data inside the DescribeActionResponse as the provided ActionDescription
func (t *DescribeActionResponse) FromActionDescription(v ActionDescription) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionDescription performs a merge with any union data inside the DescribeActionResponse, using the provided ActionDescription
func (t *DescribeActionResponse) MergeActionDescription(v ActionDescription) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the DescribeActionResponse as a ActionKitError
func (t DescribeActionResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the DescribeActionResponse as the provided ActionKitError
func (t *DescribeActionResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the DescribeActionResponse, using the provided ActionKitError
func (t *DescribeActionResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DescribeActionResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DescribeActionResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPrepareResult returns the union data inside the PrepareActionResponse as a PrepareResult
func (t PrepareActionResponse) AsPrepareResult() (PrepareResult, error) {
	var body PrepareResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPrepareResult overwrites any union data inside the PrepareActionResponse as the provided PrepareResult
func (t *PrepareActionResponse) FromPrepareResult(v PrepareResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePrepareResult performs a merge with any union data inside the PrepareActionResponse, using the provided PrepareResult
func (t *PrepareActionResponse) MergePrepareResult(v PrepareResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the PrepareActionResponse as a ActionKitError
func (t PrepareActionResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the PrepareActionResponse as the provided ActionKitError
func (t *PrepareActionResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the PrepareActionResponse, using the provided ActionKitError
func (t *PrepareActionResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PrepareActionResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PrepareActionResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsQueryMetricsResult returns the union data inside the QueryMetricsResponse as a QueryMetricsResult
func (t QueryMetricsResponse) AsQueryMetricsResult() (QueryMetricsResult, error) {
	var body QueryMetricsResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQueryMetricsResult overwrites any union data inside the QueryMetricsResponse as the provided QueryMetricsResult
func (t *QueryMetricsResponse) FromQueryMetricsResult(v QueryMetricsResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQueryMetricsResult performs a merge with any union data inside the QueryMetricsResponse, using the provided QueryMetricsResult
func (t *QueryMetricsResponse) MergeQueryMetricsResult(v QueryMetricsResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the QueryMetricsResponse as a ActionKitError
func (t QueryMetricsResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the QueryMetricsResponse as the provided ActionKitError
func (t *QueryMetricsResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the QueryMetricsResponse, using the provided ActionKitError
func (t *QueryMetricsResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t QueryMetricsResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *QueryMetricsResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStartResult returns the union data inside the StartActionResponse as a StartResult
func (t StartActionResponse) AsStartResult() (StartResult, error) {
	var body StartResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStartResult overwrites any union data inside the StartActionResponse as the provided StartResult
func (t *StartActionResponse) FromStartResult(v StartResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStartResult performs a merge with any union data inside the StartActionResponse, using the provided StartResult
func (t *StartActionResponse) MergeStartResult(v StartResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the StartActionResponse as a ActionKitError
func (t StartActionResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the StartActionResponse as the provided ActionKitError
func (t *StartActionResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the StartActionResponse, using the provided ActionKitError
func (t *StartActionResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StartActionResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StartActionResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStopResult returns the union data inside the StopActionResponse as a StopResult
func (t StopActionResponse) AsStopResult() (StopResult, error) {
	var body StopResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStopResult overwrites any union data inside the StopActionResponse as the provided StopResult
func (t *StopActionResponse) FromStopResult(v StopResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStopResult performs a merge with any union data inside the StopActionResponse, using the provided StopResult
func (t *StopActionResponse) MergeStopResult(v StopResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the StopActionResponse as a ActionKitError
func (t StopActionResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the StopActionResponse as the provided ActionKitError
func (t *StopActionResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the StopActionResponse, using the provided ActionKitError
func (t *StopActionResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StopActionResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StopActionResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9DXPjNpLoX0HpXZVn8mR5stnN3rnqass79mxcmUnmZjwvdbXjZ0FkS8KaBBgAlKxN",
	"/N+v0PggSIISPbHzcZtUJZFJEGh0Nxrdje7GD5NMlJXgwLWanP4wkfB9DUr/VeQM8MFZppng7zXVtXoX",
	"Xu7Mq0xwDVybn7SqCpZR0/TkH0pw80xlayip+VVJUYHUrke4g6w2LS9z8+dSyJLqyelEacn4ajKd6F0F",
	"8d93xytx7B7WNctnHz5cnsfPj1lZCYmAVFSvJ6eTFdPrejHLRHmyEmJVwIn5cHJ/P50oTTWYpv8mYTk5",
	"nfyfkwYDJxZmddLMGvAjgxYmIZ+c/r0Fv+/uOkAtFv+ATE/uzVc5qEyyyrSdnE6u1kC+urp6SxyOSUV3",
	"haA5qahSkBMtiF4DoTg0UYhxAjyvBONazQximC7MGBY6YolCHFUm99PJWwkVlWDfPw61MsGXbIVf5Tkz",
	"n9DibdRCyxpSM3XTsJ/XEgebkas1U+aZpowrnC7w/LhWINstSS44kKWQEUpm5K1Qii0K6LStqKQlaJCK",
	"UAkkhyXjBp9rKerVOkZqBOZs0iPZtCHtS4OsO32ITS667eM+fhn21lSu4CDgV7bVftZ2pH983q4sm6aZ",
	"2/EwcUwecfd/1SB3b0BLlqnHZu7+dEociHxvBv2tsvFvgQUN5UtQmpZVnxCvhCTbNdUktEE8ONpsaFGD",
	"Imot6iInCyDSPIcN5AYtYdo51XBsOujNfD//N3A9xVpo8VezEsibutCsKsC/8SApsqZVBRzZCTbmnWOH",
	"0CReRrhYiFst8Sp6r6nUj7lD/L6f76WzMvgOpEpJPKRIQt6916L6nVA/I6FEdYBOouqRCWFUleAq1pdf",
	"M6XfuccPohjlu2+Xk9O/j8GSGWRyPx3T9GumL6QUcnJ/nUCQh7SzU5GCKR1Q0dc/zfgkzPJ+2rEVnmz2",
	"YYC6eKL5J9fsHgW8QcE5drwIKvgTs8B5NI8nwUTu5rMHGX7KzdJo0NExSJ4MG26cp+SJlu5Kh5DR014b",
	"XLTV1ydDRWeYJ8NHUn8ZUkBiPLQUkKcUElL/kjKis6vH82+29Secvqiedvb9zXJwq/RzN0qAHbTZKWMJ",
	"1lP/30qxYTkokoOmrFCELkStCSWVN6EsCFMCs9Vsak2FtlUlKqs8M03WVE3JWmzNhl9JUMC1eaxFsN4U",
	"oTz3TbRkqxW0TLfJtKNSNT6RVwVdqf4MzkIDsjQtiDYgGglRO9XDgwuxlDFoVhVkbMkyklEF6vQjJ+Qz",
	"Mj+/fH/219cXN19dnL27+uvF2dWcHJNzpqjBhulhDVTqBVBNFqC3AJzQlZmpmVlVUG3UPkdGpoJFWRuV",
	"r7EkJtMJ01BatZHXpVG/eiNHype3p8IDKiXdmb8zqmEl5K6Pmg8GAQYQ14T901FsGWNiy/SacYK2NeMa",
	"5JJmoJwJzpSjLy1wfqVQuthZ1FJFVL049uMTtiQZSGOxu65jw3ElRV0hPVag1yBnk8TU8n2sGvGxtdAC",
	"S2lB1lCg4VqSmucglTbAWru2mSlTJBeMr5JjrxnX43Tnr0zL++mEZSkwzzgxLywbMhW4kOXANVvuyE7U",
	"MkDEEb6azcg3ADlOxagCJKeaHteSeR+I4R3KCSvpCgz4Jb17DXxlLILPX+A/U2MgaJAGhv9vPj+dffZv",
	"qYmyPAE00ZCtOctoQS7Pe7DXnH1fQ7FrJoGsbbo2zOTdLv8tarJlRWFemK6KHdlSjuu/VkCUKMGw2ooU",
	"7BbIXMjVDO5oWRUwK3fHS8qz3THVmma38ySJbhnPx5Hoa9Pyfjop6AKK1HTXdUn5sQSa47LGdl03UgoE",
	"uyerQ1C4TfllLCjN540HKiGKG+/UKBFmVigoiL1aiHz00phFAHnDX7h4/esNLVhOtXXiBCl0GKsBwp4Y",
	"mk4si1zazrSswczWqmoHkVVrqhlfXbhd7h0sQQLPcC9HJeCn9qBr9cldfMf0+iUtiksjGje0sF2K6ifB",
	"ZB1476GAzAu7w568pnm/hysozdbj9syiGKHAXA31cH9tJHElwUj23B9A3B03z8zCUX6LIfNOTzPV63NO",
	"GFcaaD5rYL9CBvohMVTfSzJ66KbrzpBGvIlCrB59m7zkuClaHWJqBaNfaObzZmS7rNGXfaeBK7clWY3L",
	"7GGU5wVM7eZm5SKZn333fj4l86/rBUgOiEohyfwroTT+onxHslppUcYj7USN8mMrmXZbRzPmUqR3X81K",
	"eCm4lqI4yJBR0/vpZANSJffsqzUQ97KNzhl5ByWUC6P9CcJ4ZshqEYY+Z+t/NRDhXOrKyCtnLy8ZR40P",
	"dRRoVC7EOltxIQHR0rQk2ZryFSgkotWuaRko6wCcke+A5IJIyERZAs9JregKNzgF5QYksahSSeRtWb4C",
	"fVDMfOeadT1vLJ/43apBZ1shcvtfm06tLaWRuF5uXvc8KuetHnsHG5GG0yOmeapa21JlrQfSKOmEcev1",
	"NGM5t59ZMkiqHX6c2Jy2a+ChKbEnP7jfGd7dZx1ENl3ygLSmBTGKHdFwp8mzjHKvUJGSyttcbPnzGfnO",
	"Ldecqaqguwa0Soq8zjT5cGlBHAZrQEvvguVHQgT2B9HCw2ANDQO50aZJzpa4exjbq8BVn1tejl8ZtdPA",
	"4s0J8/mNocfEarc3WyqNIpmwKjrciG+nAbvXgTG+dhpYSjNfmPVlJJxh00YttBKRRQaF5x7U2a0GHynt",
	"5t+soEpZNdPIA8lErYisOaeNRRppSRWVGgc0Uq4CyUrgOsaEVSrNjNaA/y8EzW80KGNRC2OOJC2tjt2e",
	"UvWBrynPII+l3LtXL8mf//3Fn8lbKRYFlOTc2dZGsKOb/OztpeHxsiqY0Y+9e5ssRL6z4t8MSFQG3Exe",
	"9fjeWusjFFu4qwrK7XIM5i6uS2PZZVktUSfxwrmyECc52mynZq6pUT+8uyTSKzjOfLCmAgN7fBsGf9ig",
	"jfKWw5LWhZ6cThA5kE+6LpTPyJKyAnJyTKL4iDVF5wZkGnI0QbBVLc1mHe+0FJ/jygalyXbNsjV+vDAW",
	"PjNtDFtBTha7rhbe6Ah2eRv9sIJ8akxixLSLNWGKSNC15E0vnSiUGfmMuPnZaZhNnCpCIwPNMsd2zZC+",
	"6E9oy6Mg0IyMs4Z6JG/9fvnYkEfrzdLBPHCkSvox7MbUZya1FlJPu5ys6rKkctdhGrRBHyCAx7Dqga67",
	"shKnEW20zsk3jQ6q+nCYp4rQomhLs5g+J9arlKEHxdIZEv4x+7n5OcqSc7J60DA5ZNV1Zu+Hv06eXQ1r",
	"GI0p2TtEpVkGlYb8FSvAKPIJU/kDgkWWZgWgE8JJF7OV5GGCzv/jnBSmsdVe/AC4/CPr2XCWaXxkmh61",
	"bOP9Tri09UvzDW4NCS1gjS4wu8ACAJGzrCqo2VNwV3QGQ0W5XQe+W6KgZZg06pM3TiLeXQhRAOXWx4Zy",
	"9P8ZLTu1Ptx7p4YHN2YA0+3j9vW2pc8sGyByAYpwoR1ldoQOd5j2BDZG4RD6hMQROlhkhgX8xzNyHn6n",
	"HCVrlufAyVIa86mHwL7SRwmHLVEaqhm5uGMKJa/503WptOvYOout3ytPgTAjZ8kXngvMzNCTY9ca4UKS",
	"Nd2gbzCi4BCNbcdM8DegjBWTonRpX1nJEzaAtdi2NPegnFvtfUAF9gFbBvR4V2U8K2pjITg13GKEEgnI",
	"415Re2pPcHy8uJ/vnLPuA2c6IXjO49fkvZM6dtuo8VlQSg9KGT/UkWFSpKgVT0clKwqmIBM8V0dTchT9",
	"LBmvNaij0Y67GOCRcuvhjvCf4mU9QI+S3g1IKowgZJyVdblHVn3Lix1xx30GhAFizM2aX4GcT8m8ApkB",
	"13QF8ylaI3NPqTl6ewzsGVW4qTSvppHvwpg5nMRkjObmRsLJMf6/d3KclgMTu4Wd29qskp1iBoKqp9Ed",
	"nWgxHxnzXRtptDBzrZ0NHMxoGxfgQpCOvBOBLBkUeZK53MllH8pv/ZGXP9v0PDu3HxtM2l9/v55bNNo/",
	"b3BhzaN5mEHVjHyHM5V4Xmzwp+rVClTTeRBhM3LGjZJ7+pGTYzK3eLm5ZfqGVmx2cWeIzXRQnyyk82Tj",
	"TiP1SorS+kvPtJZsUWuYj5Ujnb5GihKHPsOnLRMuFdJ+jtG4Rokw+KCWdf+THFnEHll3h+sQzRNhuN8Q",
	"xROp0Z9oUYgt5OgfLZQgSwmALqAgag1/GSjS+6eQOci9vmnP6EPOaXRMCsXiUz4M9sJ91tijsjTTRfjN",
	"aOilbjTrAzpPs+NxsM6UB+lZ0VQH/FSxH8d22FezMlppVASsJWkVce+JJ4wvi9qYFXZ3nNvVOPchgVQF",
	"tw2+DvFFuHqNMNKWdnbNoNBhZSXFxijGCuRxo6aBNc1VbIKGwwO/TsPPG8+xDQ09PqaTRj5OGmVgMp0Y",
	"k2AyndzC7gbRYRheFgajcKepBGq6t3FLwvS4BprbrpmWVFuPrASl+Op4K+StdddKWMHdxB+IHAfkHfbQ",
	"eVcxSlnX+LoVIAgPyygxUqfjuAsuGwwEbauJ7cBODnf6YCINJK1BqdmSZgkL+czZxSXdkWwthIKWx9l9",
	"p8gzKhHHcmdNvOeNClZQw6lGEXOxLIud8zeiTsu4maG2YRnebdhEaPiQmKDbloBcuKY832FMy11loMJA",
	"V/QZSaiE1DbERbGSFVTiQX7fajdP+1NeUAVf/pEAz0QOOX7aPur/8j/+/MWLL14ktrIBFeyrvQqYwyEe",
	"fDSnHvY8BrX2pXUxuYMjFW+3TVeULEAbROOqtJhE3woiORdbbjDk7AUVkc7HFAVn7I1d6zNN5Wz1z06Y",
	"wx/+9OXYRYGIiz0Snsn2MOB4D0ro7b4/gpr043PcjvPXgir9juasVmm1yBveC9OQSGzZCbXq5rk8c32f",
	"ks9fvCBOdj3vcVsp8iEdU+TBDSspz0XJ/mk0y8slUYDmWltj1L3ztoplt4T7sX1fVpIZAYGSTbV6LOmd",
	"UWxdd82wvi//TSTNW2LZfZ90Km7S+vSlBQunazTLobkFFRcnGt7unVaq4/YUW73yGk89TY/NPLvqc4ex",
	"kYB+ctcJLt7n1esLhaurt0FaRzr4ew003y2YTrsgjXyoOTOKDgqCvlQrQa/FwQidd0Dzr7Su3tjWGBVj",
	"FnhvA1goUdTa7DVG87OIbsGOEDRBTyfJgKcOKnGsqQc1EhLYs8ceaTlFW0Z0D85f1gvgV0jcHHUR/8s1",
	"NjqJqFHryOlO9ReP0WRNZ8cbKo1WoTAiMZr5m/YI8av3yadvwsjx068cFPGzc4TofjqJ0j3LktqzxnHh",
	"uN0v34N2Ks/O2tg2qqXtn8hsW0suY10umrPtUuT+BDKpHTwzmxdpFsBzZ7h95CRpuO0Hbz7us3MoQMOn",
	"fHmW59j8SrxmKow9j1S1Hu4T9Ej3kgzKVcEU0YJQa/w4bO1iRSKF3CMVIbYvZ3w3X8Nu2MPQnBNh2442",
	"8eUfRx8ZBdvG9eiYph2x6QV/hwoDWG+dTee5NSlutLgxWLrxIO/f4B6WLN5QIs8TGa3p8/8Yz/HuM8Aw",
	"A8yR2K5GsHXK62saRRuqsVT+9VgqJQJifsrxfWCim67SsD/kI8bDHlKnCDaCzj2h3N9MQf/LU7i3N7T8",
	"GqAP0/aniwkF+qnERI8JRjBOKu/Dbili6XGr/rW38VG2a2qPH6JTypa9SJTv6HNRg93MNmsqOcThgS7w",
	"1awOjAiKydIOFu1HPRi75GyrzrJM1Fxf5mlAzr57bzRw04RcnodO0ajxOQ7pCJqQ/MKLHa7TEKLY5JK4",
	"mIycmLnweLDUYQOO+pYNQFpJkYFSD4Myee7SyUHfR51msB4BDvT9QbJDnX94dzmm9wZBzfIcFNHRCo6k",
	"dfTUo8uNWOzIApq0K8gPDLxnWmGIaF4/dWAJ5nemIfd2Z0LOhVedrBAfhYZsYqSYzRNp2+ix8y5OT3vu",
	"k0deCs4hJGvRovCBB3S5tK6OxS6EKJ0QG0ipRh8/v+vNsJ/Bdp+U/8lzrj52/lvUKPExqgDDP/G7kyW7",
	"a0VViCZagJJbLracnBAMD7fbsFiGYyREM4cNSBc23hc/DzvwjiKSbNhlNbgGNsPHwU38nwu9Qb9N2h/v",
	"ZFT3jMUfwVg8Hw5tC/Hodku/n05eMw4v11RqG8eeQoENhLdYVGuxVWj8cTDIlLqPS0wMNKMfYKXO0H9z",
	"n9kUK5vXBlwza40+oKNL91nT0UBgIhLBvPL4tDN1e8V2KIbc4cMeCHVT9/7w7ymNUohCs+qB87iyX0XT",
	"GKWY+kmM0EtfijK4CO2YAYSWipqJcqZ8w5kbwLDADbLAaFvE0iEibKRUdhkxIUNSDJNiWGRAg46cakqc",
	"rA1HtsOMi5H4aQTbIH2HYey/wyVNXl/hk/2pzjA38iAUoaqMBSAZNKOztT3AfuiKeuM+fcAySM2vtwoc",
	"TxMfjFUxN6NuXO+2Q8+9UbfTgAM/5WEWsfQfySdvGgyOcz/u6eQVLYoFzW4PlgnY08fXsLv4vqaFcr7M",
	"T+/pG6EvykrvEv7QK8+GGHRqxbcLqAjWlHlt07AiNu00bvYcpjx3BKOqb+KMQN38oR+28fXgzz2S5gf4",
	"I5A2IVaW7l0bpbhALBaNstXDolHvjAZmP7Lal0EdBn9YXPYE0c8p6JPUeYDwn+EcbhxObjySRu4J1w9b",
	"vp1VkwqBHUmbLSZitBxTUVIL5GiOAI7VebHxUbptmt1aE+cTvUmPT8vOgvl0it7C7sYiYox3apQecNvx",
	"Kz2AA4K0e2raMxvtDmawXz+1g3z7dDpzoW9wtqPVuVvYjSZfo9gPx2a2QyO0cIocpnjtV6IIjqG8qxB1",
	"CLCZhzToI+6ljYdn6OF5G5QWDHhyxtZB42av89K26G6hPf0phv6CZms32eQMPGO7l6HM6adv32PN/aTK",
	"lShZY5D63uI5GavhuVvLGuOUI3WxnacwQAebF97+RmHRoXUvkcwRANNO267jJSs0yMMKeTeossP+jgcO",
	"aKYNxx9eIh2TtZdBtZSiTIsVTkt3quKKi2FwdKvIjCv20iTFSVIZLIDCPJRm6vF5zIfLPdVSvhmMBPfg",
	"NNXOetyYCa6YzRcPIa1J9EejJsOdbKSOBFSxSl8C1hW4XewImJ9YsYPMDQLntpKVg6SRwyousPIXq1ke",
	"Ep3egr0xoLnyGHNyTM6IYnxVBCcBZlm67HhvKdmax5S74KNoIzokMxwcnwKifX9cgTzGsRywNsA1Ca7h",
	"kRXbAG80nrEbSwo7aNr9FIgPb0sRc07tknGsM7xSOwvv8EptO2X6qY7hcO7lUCGDqLyZS8c/SHdna/u4",
	"1bZQQzE4UK+hOZA5KPM+ZTtokIFTTewLliT2gCvtfQi7f8sFEVerHo2eYYGFAKSDvcL4NWf6kYfvptb2",
	"mGOYMdt89hC+9Fz3eDtII6CaGng9Jh4oQDPO45Tobsj9RG2aQhw866IxDzNDPYIDrBc+yjzJc8hbasnI",
	"4Qb8W0iIMXRHOqYIL1YP8dUXYuXzQhMxFIVYXR00WfznY/enxq6x6ulcu+pNPevG5bLOx3nRf2kv/s9g",
	"24nVCAtOjC/44uk77Vc1aPgowWRvXC2dcZxmdQZF/FexTOjsj1UFqYIzfRMhohHS0H7pQm/ctincoa1L",
	"2/bPxZJUEjZYYyZERWe0KNSMvGpSmadYiMrsprYQhjU0DUMwvgq75BzrLs3x+6mHAltWUqwkqHYIRPSV",
	"rpX9zNoiNI+N0aadqGyrVkT9khYqhQUbveANH8wrUPWiZFpDHua/MKtuGgp0LnZkHu5lmM/It0VuL93A",
	"xr0FMnVJ8gXLbg1WhRN0rATUGBzksuZkw2A7I1fC53H5IHtEB88chp3AQNAdpoNEYcsWRddGuuMRLUan",
	"V1Q2R6CBpDi9dO6b6/d3kfbrEWleJhyWa75+14OPE2OqT72IiSRdR5ilxN1QTYXXYnWcrKrQPp4PGTTP",
	"fM6PjeIoxOp5XwiigjWi4igO+8o2vp9OCtj4GAVfOMnVAmsiRRf1CvMg8fGWSu5L9iS9tmUz7WTtwHDD",
	"zJh7YaJP3otaZjCm5GDcvMWPfoZnf7v45mpy2PKzE4mJ7h4NU/tVIEM6pPKHA0Us9mZYWhq3eaZbJy9w",
	"jT9LFUvS2pXbUyEO4OEZqb0MrH4KB48yDz3O73uwp0IPbUndPsj+Ah5n59qkzDhsyYc6lVFDX0XALBJJ",
	"V7Z9q4yISw4laqc0lGQBa7phrvKeFqEodrEzVrPU6eBSuzW6mth+fCqBiIUCucE6WzOYTVuw0Uwbs+WZ",
	"lXg2+fY5wcp1Kplz5dDyiWz5NexOrI1SUdaun9TYtm4vQTHPFKa7Fca6WmqQ5K3Ews5QqyPrOMDX7anZ",
	"UChla0SXdOeSXGPzGS1Lqsj85sb8vLmZhyRaLdAX1wxk6wsxnbycK1154k0zioUCcV1okJxqtoFiJEyR",
	"19M1iqPF9wvGzsYZbtyKcE69TVkKF1joTcgtVYFvxt6+9RhStntYZxMYO5cXLQtB9Zd/TNixzQ1fjlUT",
	"IeJv/JuEqAr1tkfKFOzpvtv3sETpFOnuuULw+o2R9b7xRo5O0e8+KKTdYnjWie76V075uMrHrG/dLlP+",
	"ZBXCu7dPNbdcRABc9/FnLz45jMXBCty/tpRYD+lvKy12PEuNrkm+r2h672rJzggdNGlb/m+J9YB4totP",
	"cmxBi0DvBaBJDflfyBW9BUV8Um4w662sxaJIn794Uboi3J+/UPMOsj9+zP/vM65+LNWP6sfyx/WP+fM0",
	"8jvc2gvGekSOfAApIwaM7iV5++17o1S//WD+e37x+uLqImkgJKK1xybvpsO9D8W5jahwNLm/7kOWbJis",
	"kKepDx13rit3rY2t3Wkz+An1ffjjRO9qvoVd+pbR8EEoTtVxfA1DddUd0wyCBQwbJgmX93QD4K32uaJ4",
	"EpqPOIMIcFzbu8bcbIYcfa167CHph/oQ+zWeskujNuakCr35k9XgsbC+QqNsYiUn5esGCu69DGUqwa8N",
	"nc1/+TU4NRq8HXZrNLN4QM5mb+LXrfvS2kRL7JTty936x5RxjZQxpVHQAZFFqXsPyUnDj8FX3H7IvVrB",
	"RTHW9FQPv9Jl8hj3bA7drNm7wu4RyfFzoMbMs1PeI9pG/naRvtAqkSTUv0ea5akC7OTl5fm73nVFPq/K",
	"eqKtvGwKk2E5guB54aC3Qt52tvFnf39x/B/XP3w+/eL+48fZ8x++uG8ePDvxv/9w//wvySuW+KiIl0oK",
	"V5b8IlT/fiVkU536BD10K2MWVrWshAKbkJg0NCsh9Rt6N1Dnx9ajIaaRr0DjseaL5VmhVqsQaQMNXFHV",
	"ndMv//SnL/6EdUXs3y9SmYIIDeP7K1v+bNDUskhD8uHd6z3UOLg9uuprthIcsmgz84YiqXUeX574u7x9",
	"CnmbQrmGbzcgr1gJD8tfs/aCWBKxMazKykRE99j0swQY/RS0kGD4wJ5em++abkYhLtENPvrNJcQlJvJL",
	"JMW1wDis8CGNbgxj3aAPL7VDOvn1wMl/kBErBC/eAzvBWCjfzcg8veYmI0+5+DLx5vbW3nIct2p/yfBX",
	"G/kqxfZg9GsHV91AnsPzGoeMeMU/MiaSycw/FzLieY3DRCy0Hj2gzZcwsDsB1ZiV5TeCnzzZGPRxkz0Q",
	"WPpY0w1pm4884YPxinvF2SPz+Yd3r2fkuzVwQjeUFYbZp4RpktHaaNzUJ6rCqvRxRLXkhHG0JNa7CmTB",
	"+G0aMXuQ0ExoHAJiUdxDwZrlQ+WUBFa6xkM01j7e8pd4hMXb2sGtRbWsC3uOGepta0m5KvDaCrscWhFN",
	"ikgoYEP5UG7EHozEMxzASa1+RVozXuEFyUtKmtocqAgZhmPcUqESRZG6QYlQRQphWNJdDmZ6NgjF8C48",
	"eebC3f5ka40mo5r+d7tOGpRfu5vef7eixrpmrOt4QP21bhIMWkA3ssBABFtFJChDNq7C6PSZ0Vh3ezzX",
	"e0NlRl6sdJ9IUVeR+1yFStW2VjcaGal8Bjc7Vz287YxvJkN63VMJ0WXW/tbzKP68dadQEKO+RpS/NI52",
	"Cr70YxVG+Rki3KZ8Clf9S4UTF91GdwX4mxUphroob/10PWahyrG/yl7wI20vHqC9xu4GXLfN2pgcYSNO",
	"E2XQk6Wx919f1vsCL1JRivEVOk/3zD+ust34A1uzDid+Hy4JWxp5i+f/Rt4G5nGVl+y1pp+RI8eDN7Qo",
	"jshZOBZqTOBQNnqxC+NH33HB4ShEUj0n34gxPUR2ZQQAhvM13Y4s8/smhb9L288ZdrqvxTc40P108n1N",
	"0YDxDt0kEb4SW1KiMunm2ITTxrNsMIxKgTolHzn5jMzhjma62N0IjklpF/ZPPBlyrFjWSse92WzQKCjL",
	"4HRJWWEIXArM7aY87gE3V/exHZUWBabAFUWvBnirposdq2b2Id5/hvlWcS3xqOC592z2VpwdlbtJOqaf",
	"ufsgbY2I4OV2ceR4n1bosV9lvAXZp0EVsVxEBiOYkEcewHD/1ecUR8lvscPEe8uHiReB/VTyMvRPuwK9",
	"f0l573oUhx70G9ksJxfUGfhZ4M286MCeEZt67y5DYfnciUi3a8z9HbpXYdh37lbYEHJ27jeqr9kI33QE",
	"f2SLdfeIw9uIR0pfwdp7R9trwVcgE6cvrjsSNe/kWdirNQrqc6bcF0fKn4J0nYYv/vDHT74SAy8btb6N",
	"Ub7IEA42qEI1cw1bhz/nro0MbUI4jpRrUlC+qukKWog4/cgJoVs1c0Ul//Pj5OOEnH1zjg//KTjMWI4P",
	"P3LzGYqytPrTHmVKqgJvW/cxrjFAucjqoLIgCGutK3V6cpKLTEXuy0yUJ7WC4/DkBEc59qN85COoNFBw",
	"ziJ5mG0DT45nX5VUh6SPcqbWsPc1JbCYYHTxf1B0zHoKdy5ZsiaUoJZ+aZH/4ZII2SP3RVOe0ehKrsP+",
	"alGd+7J9w9po6p3Bx1dnHMLq/UHEp8Ipr6Jr6Qdv8zGzBIbVjBaIZHurtKYcMP9qA1z7e2Ewbwgwocq6",
	"cNZC6Sle6mWJs2F6R1RFOTpy8GyGclLzpjSLD+SyC0uvhWquD1/TjfX/+EZTsoXmOnVmhNQC9Bavf+YY",
	"J1wUOw/cljLMIrMVJXOoCrHz7qEl40yt7f16cLf/S7w0pwFYs9L6CKhSU/QaSFEU0Uxa16K0kOdutDKD",
	"mSZu3OR5wlU/KLjjN8LnQTX2zdOOoVYTd1O0ZLAxO58UpU1/sxWsbDQ9GhTN5bDM3tTmyifNQ8nSOek4",
	"UWj+D6Pbtcezy9Oo8UsFmLiX1dY5FW51Dfer54am9uCpqUTnwpWOVOP1dG7ORtlxEB3Ca3OqOC7uLXUG",
	"crC2W0j5ONSyk8h0MJiuGyj0wCpzyRs24tNUZw1281qizAl3P+KGwdblFrSu9MeEP7u4jKq9r1B3ArMD",
	"FbYDPgfet7E40KiLu6Gx2hiLb98IOHe/9hYN8pVIfkfrEFpH7X8NzttU6O9u9+gZ5Kp29ou7dNVAcfIP",
	"ZS/swzS60x8mBcuAK2hiApYM5OR08ubyyl/YZ/9o+cJ9VG/wDpKzt5eT6WQDUlnyfz57MXthry0FTis2",
	"OZ18Mft89sJGLq3V5JTXRYEulrzOhuC8/58AAAD//6MYC12QpAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
