// Package action_kit_api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package action_kit_api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ActionDescriptionAdditionalFlags.
const (
	DISABLEHEARTBEAT ActionDescriptionAdditionalFlags = "DISABLE_HEARTBEAT"
)

// Defines values for ActionHintType.
const (
	HintInfo    ActionHintType = "hint_info"
	HintWarning ActionHintType = "hint_warning"
)

// Defines values for ActionKind.
const (
	Attack   ActionKind = "attack"
	Check    ActionKind = "check"
	LoadTest ActionKind = "load_test"
	Other    ActionKind = "other"
)

// Defines values for ActionKitErrorStatus.
const (
	Errored ActionKitErrorStatus = "errored"
	Failed  ActionKitErrorStatus = "failed"
)

// Defines values for ActionParameterType.
const (
	Bitrate         ActionParameterType = "bitrate"
	Boolean         ActionParameterType = "boolean"
	Duration        ActionParameterType = "duration"
	File            ActionParameterType = "file"
	Header          ActionParameterType = "header"
	Integer         ActionParameterType = "integer"
	KeyValue        ActionParameterType = "key_value"
	Percentage      ActionParameterType = "percentage"
	Separator       ActionParameterType = "separator"
	StressngWorkers ActionParameterType = "stressng-workers"
	String          ActionParameterType = "string"
	String1         ActionParameterType = "string[]"
	StringArray     ActionParameterType = "string_array"
	Textarea        ActionParameterType = "textarea"
	Url             ActionParameterType = "url"
)

// Defines values for LogWidgetType.
const (
	ComSteadybitWidgetLog LogWidgetType = "com.steadybit.widget.log"
)

// Defines values for MessageLevel.
const (
	Debug MessageLevel = "debug"
	Error MessageLevel = "error"
	Info  MessageLevel = "info"
	Warn  MessageLevel = "warn"
)

// Defines values for MutatingHttpMethod.
const (
	DELETE MutatingHttpMethod = "DELETE"
	POST   MutatingHttpMethod = "POST"
	PUT    MutatingHttpMethod = "PUT"
)

// Defines values for PredefinedWidgetType.
const (
	ComSteadybitWidgetPredefined PredefinedWidgetType = "com.steadybit.widget.predefined"
)

// Defines values for ReadHttpMethod.
const (
	GET ReadHttpMethod = "GET"
)

// Defines values for StateOverTimeWidgetType.
const (
	ComSteadybitWidgetStateOverTime StateOverTimeWidgetType = "com.steadybit.widget.state_over_time"
)

// Defines values for TargetSelectionQuantityRestriction.
const (
	All        TargetSelectionQuantityRestriction = "all"
	ExactlyOne TargetSelectionQuantityRestriction = "exactly_one"
	None       TargetSelectionQuantityRestriction = "none"
)

// Defines values for TimeControl.
const (
	TimeControlExternal      TimeControl = "external"
	TimeControlInstantaneous TimeControl = "instantaneous"
	TimeControlInternal      TimeControl = "internal"
)

// Defines values for TimestampSource.
const (
	TimestampSourceExtension TimestampSource = "extension"
	TimestampSourceExternal  TimestampSource = "external"
)

// ActionDescription Provides details about a possible action, e.g., what configuration options it has, how to present it to end-users and how to trigger the action.
type ActionDescription struct {
	// AdditionalFlags Additional flags that are used to configure the action for specific cases:
	//   * `DISABLE_HEARTBEAT` - Disable the heartbeat between agent and platform for this action during execution
	AdditionalFlags *[]ActionDescriptionAdditionalFlags `json:"additionalFlags,omitempty"`

	// Category Used for categorization of the action within user interfaces.
	Category *string `json:"category,omitempty"`

	// Description Description for end-users to help them understand what the action is doing.
	Description string `json:"description"`

	// Hint Hints are used to provide additional information to the user. They are rendered in the ui when the user is configuring the action.
	Hint *ActionHint `json:"hint,omitempty"`

	// Icon An icon that is used to identify your action in the ui. Needs to be a data-uri containing an image.
	Icon *string `json:"icon,omitempty"`

	// Id A technical ID that is used to uniquely identify this type of action. You will typically want to use something like `org.example.my-fancy-attack`.
	Id string `json:"id"`

	// Kind Describes what kind of action this is. This is used to help users understand and classify the various runnable actions that are part of an experiment.
	Kind ActionKind `json:"kind"`

	// Label A human-readable label for the action.
	Label   string                `json:"label"`
	Metrics *MetricsConfiguration `json:"metrics,omitempty"`

	// Parameters Parameters that are used to configure the action. These parameters will be rendered in the ui and will be validated.
	Parameters []ActionParameter `json:"parameters"`

	// Prepare HTTP endpoint which the Steadybit platform/agent could communicate with.
	Prepare MutatingEndpointReference `json:"prepare"`

	// Start HTTP endpoint which the Steadybit platform/agent could communicate with.
	Start MutatingEndpointReference `json:"start"`

	// Status HTTP endpoint which the Steadybit platform/agent could communicate with.
	Status *MutatingEndpointReferenceWithCallInterval `json:"status,omitempty"`

	// Stop HTTP endpoint which the Steadybit platform/agent could communicate with.
	Stop *MutatingEndpointReference `json:"stop,omitempty"`

	// TargetSelection Used to specify various aspects of the target selection. If the action don't need a target selection, this field can be omitted.
	TargetSelection *TargetSelection `json:"targetSelection,omitempty"`

	// TargetSelectionTemplates Deprecated: use `TargetSelection.selectionTemplates` instead.
	// Deprecated:
	TargetSelectionTemplates *TargetSelectionTemplates `json:"targetSelectionTemplates,omitempty"`

	// TargetType Deprecated: use `TargetSelection.targetType` instead.
	// Deprecated:
	TargetType *string `json:"targetType,omitempty"`

	// TimeControl Actions can either be an instantaneous event, e.g., the restart of a host, or an activity spanning over an unspecified duration. For those actions having a duration, we differentiate between internally, e.g., waiting for a deployment to finish, and externally, e.g., waiting for a user-specified time to pass, controlled durations.
	TimeControl TimeControl `json:"timeControl"`

	// Version The version of the action. Remember to increase the value everytime you update the definitions. The platform will ignore any definition changes with the same action version. We do recommend usage of semver strings.
	Version string `json:"version"`

	// Widgets Widgets that will be rendered in the experiment result view after an experiment has finished.
	Widgets *Widgets `json:"widgets,omitempty"`
}

// ActionDescriptionAdditionalFlags defines model for ActionDescription.AdditionalFlags.
type ActionDescriptionAdditionalFlags string

// ActionHint Hints are used to provide additional information to the user. They are rendered in the ui when the user is configuring the action.
type ActionHint struct {
	// Content The actual hint text (can contain markdown). Will be displayed in the product UI when configuring the action.
	Content string `json:"content"`

	// Type Will be used in the product UI to display the hint in a different color and with a different icon.
	Type ActionHintType `json:"type"`
}

// ActionHintType Will be used in the product UI to display the hint in a different color and with a different icon.
type ActionHintType string

// ActionKind Describes what kind of action this is. This is used to help users understand and classify the various runnable actions that are part of an experiment.
type ActionKind string

// ActionKitError An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
type ActionKitError struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status * failed - The action has detected some failures, for example a failing test which has been implemented by the action. The action will be stopped, if this status is returned by the status endpoint. * errored - There was a technical error while executing the action. Will be marked as red in the platform. The action will be stopped, if this status is returned by the status endpoint.
	Status *ActionKitErrorStatus `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type.
	Type *string `json:"type,omitempty"`
}

// ActionKitErrorStatus * failed - The action has detected some failures, for example a failing test which has been implemented by the action. The action will be stopped, if this status is returned by the status endpoint. * errored - There was a technical error while executing the action. Will be marked as red in the platform. The action will be stopped, if this status is returned by the status endpoint.
type ActionKitErrorStatus string

// ActionList Lists all actions that the platform/agent could execute.
type ActionList struct {
	Actions []DescribingEndpointReference `json:"actions"`
}

// ActionParameter defines model for ActionParameter.
type ActionParameter struct {
	// AcceptedFileTypes Unique file type specifiers describing what type of files are accepted for parameters of type 'file'.
	AcceptedFileTypes *[]string `json:"acceptedFileTypes,omitempty"`

	// Advanced Whether this parameter should be placed under the expandable advanced section within the user interface.
	Advanced *bool `json:"advanced,omitempty"`

	// DefaultValue A default value for this parameter. This value will be used if the user does not specify a value for this parameter.
	DefaultValue *string `json:"defaultValue,omitempty"`

	// Deprecated Whether or not this parameter is deprecated. Deprecated parameters will be hidden from the user interface when configuring a new step. Existing steps will still be able to use deprecated parameters. A deprecated parameter should not be required nor have a defaultValue.
	Deprecated *bool `json:"deprecated,omitempty"`

	// DeprecationMessage A message that will be shown to the user when they are configuring the action. This could for example include a hint to use a replacement.
	DeprecationMessage *string `json:"deprecationMessage,omitempty"`

	// Description Description for end-users to help them understand the action parameter.
	Description *string `json:"description,omitempty"`

	// Hint Hints are used to provide additional information to the user. They are rendered in the ui when the user is configuring the action.
	Hint *ActionHint `json:"hint,omitempty"`

	// Label A human-readable label for the action parameter.
	Label string `json:"label"`

	// MaxValue The minimum value for this parameter. Only applicable for parameters of type `integer` and `percentage`.
	MaxValue *int `json:"maxValue,omitempty"`

	// MinValue The minimum value for this parameter. Only applicable for parameters of type `integer` and `percentage`.
	MinValue *int `json:"minValue,omitempty"`

	// Name The key under which the action parameter is stored. This key can then be found within the prepare request's config field.
	Name string `json:"name"`

	// Options Optional options for the `string`, `string[]` and `string_array` parameter types. Which result in suggestions for end-users.
	Options *[]ParameterOption `json:"options,omitempty"`

	// Order You can define this fields to order the parameters in the user interface. The lower the value, the higher the position.
	Order *int `json:"order,omitempty"`

	// Required Whether or not end-users need to specify a value for this parameter.
	Required *bool `json:"required,omitempty"`

	// Type What kind of value this parameter is capturing. The type selection influences the `config` passed as part of the `PrepareRequest`. It also results in improved user-interface elements.
	Type ActionParameterType `json:"type"`
}

// ActionParameterType What kind of value this parameter is capturing. The type selection influences the `config` passed as part of the `PrepareRequest`. It also results in improved user-interface elements.
type ActionParameterType string

// ActionState Any kind of action specific state that will be passed to the next endpoints.
type ActionState map[string]interface{}

// Artifact Actions may choose to provide artifacts (arbitrary files) that are later accessible by users when inspecting experiment execution details. This comes in handy to expose load test reports and similar data.
type Artifact struct {
	// Data base64 encoded data
	Data string `json:"data"`

	// Label Human-readable label for the artifact. We recommend to include file extensions within the label for a better user-experience when downloading these artifacts, e.g., load_test_result.tar.gz.
	Label string `json:"label"`
}

// Artifacts defines model for Artifacts.
type Artifacts = []Artifact

// DescribingEndpointReference HTTP endpoint which the Steadybit platform/agent could communicate with.
type DescribingEndpointReference struct {
	Method ReadHttpMethod `json:"method"`

	// Path Absolute path of the HTTP endpoint.
	Path string `json:"path"`
}

// ExecutionContext The execution context contains information about the current execution of the action.
type ExecutionContext struct {
	// AgentAwsAccountId The AWS account ID of the agent that is executing the action. This is only set when the action is executed on an AWS account
	AgentAwsAccountId *string `json:"agentAwsAccountId,omitempty"`

	// AgentPid The process ID of the agent that is executing the action.
	AgentPid *int `json:"agentPid,omitempty"`

	// ExecutionId The execution ID of the current execution.
	ExecutionId *int `json:"executionId,omitempty"`

	// ExecutionUri The execution URI of the current execution.
	ExecutionUri *string `json:"executionUri,omitempty"`

	// ExperimentKey The experiment key of the experiment that is currently being executed.
	ExperimentKey *string `json:"experimentKey,omitempty"`

	// ExperimentUri The experiment URI of the experiment that is currently being executed.
	ExperimentUri *string `json:"experimentUri,omitempty"`

	// RestrictedEndpoints Endpoints that are used by the agent (e.g to communicate with extensions and platform). These Connections shall not be affected by actions / attacks.
	RestrictedEndpoints *[]RestrictedEndpoint `json:"restrictedEndpoints,omitempty"`
}

// ExplicitParameterOption You can use an explicit/fixed parameter option for a known / finite set of options that never change.
type ExplicitParameterOption struct {
	// Label A human-readable label describing this option.
	Label string `json:"label"`

	// Value The technical value which will be passed to the action as part of the `config` object.
	Value string `json:"value"`
}

// LogWidget A widget that shows log messages.
type LogWidget struct {
	LogType string        `json:"logType"`
	Title   string        `json:"title"`
	Type    LogWidgetType `json:"type"`
}

// LogWidgetType defines model for LogWidget.Type.
type LogWidgetType string

// Message Log-message that will be passed to the platform (default agent log).
type Message struct {
	// Fields Any kind of action specific fields that will be rendered in the platform tooltip of LogWidget
	Fields    *MessageFields `json:"fields,omitempty"`
	Level     *MessageLevel  `json:"level,omitempty"`
	Message   string         `json:"message"`
	Timestamp *time.Time     `json:"timestamp,omitempty"`

	// TimestampSource Source of the timestamp. This is useful when the timestamp is retrieved from some other system. If not specified or equals `extension` the agent will adjust the timestamp with an offset calculated from the response date header and the platform's current time.
	TimestampSource *TimestampSource `json:"timestampSource,omitempty"`
	Type            *string          `json:"type,omitempty"`
}

// MessageLevel defines model for Message.Level.
type MessageLevel string

// MessageFields Any kind of action specific fields that will be rendered in the platform tooltip of LogWidget
type MessageFields map[string]string

// Messages Log-messages that will be passed to the platform (default agent log).
type Messages = []Message

// Metric Metrics can be exposed by actions. These metrics can then be leveraged by end-users to inspect system behavior and to optionally abort experiment execution when certain metrics are observed, i.e., metrics can act as (steady state) checks.
type Metric struct {
	// Metric Key/value pairs describing the metric. This type is modeled after Prometheus' data model, i.e., metric labels. You may encode the metric name as `__name__` similar to how Prometheus does it.
	Metric map[string]string `json:"metric"`

	// Name Metric name. You can alternatively encode the metric name as `__name__` within the metric property.
	Name *string `json:"name,omitempty"`

	// Timestamp Timestamp describing at which moment the value was observed.
	Timestamp time.Time `json:"timestamp"`

	// TimestampSource Source of the timestamp. This is useful when the timestamp is retrieved from some other system. If not specified or equals `extension` the agent will adjust the timestamp with an offset calculated from the response date header and the platform's current time.
	TimestampSource *TimestampSource `json:"timestampSource,omitempty"`
	Value           float64          `json:"value"`
}

// Metrics defines model for Metrics.
type Metrics = []Metric

// MetricsConfiguration defines model for MetricsConfiguration.
type MetricsConfiguration struct {
	Query *MetricsQueryConfiguration `json:"query,omitempty"`
}

// MetricsQueryConfiguration defines model for MetricsQueryConfiguration.
type MetricsQueryConfiguration struct {
	// Endpoint HTTP endpoint which the Steadybit platform/agent could communicate with.
	Endpoint   MutatingEndpointReferenceWithCallInterval `json:"endpoint"`
	Parameters []ActionParameter                         `json:"parameters"`
}

// MutatingEndpointReference HTTP endpoint which the Steadybit platform/agent could communicate with.
type MutatingEndpointReference struct {
	Method MutatingHttpMethod `json:"method"`

	// Path Absolute path of the HTTP endpoint.
	Path string `json:"path"`
}

// MutatingEndpointReferenceWithCallInterval defines model for MutatingEndpointReferenceWithCallInterval.
type MutatingEndpointReferenceWithCallInterval struct {
	// CallInterval At what frequency should the state endpoint be called? Takes durations in the format of `100ms` or `10s`.
	CallInterval *string            `json:"callInterval,omitempty"`
	Method       MutatingHttpMethod `json:"method"`

	// Path Absolute path of the HTTP endpoint.
	Path string `json:"path"`
}

// MutatingHttpMethod defines model for MutatingHttpMethod.
type MutatingHttpMethod string

// ParameterOptionsFromTargetAttribute A meta option that represents all target attribute values for the key defined through the attribute field.
type ParameterOptionsFromTargetAttribute struct {
	// Attribute Target attribute key from which the possible parameter options are gathered.
	Attribute string `json:"attribute"`
}

// PredefinedWidget The platform contains a set of hand crafted predefined widgets. This widget type allows to use one of them.
type PredefinedWidget struct {
	PredefinedWidgetId string               `json:"predefinedWidgetId"`
	Type               PredefinedWidgetType `json:"type"`
}

// PredefinedWidgetType defines model for PredefinedWidget.Type.
type PredefinedWidgetType string

// PrepareResult defines model for PrepareResult.
type PrepareResult struct {
	Artifacts *Artifacts `json:"artifacts,omitempty"`

	// Error An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
	Error *ActionKitError `json:"error,omitempty"`

	// Messages Log-messages that will be passed to the platform (default agent log).
	Messages *Messages `json:"messages,omitempty"`
	Metrics  *Metrics  `json:"metrics,omitempty"`

	// State Any kind of action specific state that will be passed to the next endpoints.
	State ActionState `json:"state"`
}

// QueryMetricsResult defines model for QueryMetricsResult.
type QueryMetricsResult struct {
	Artifacts *Artifacts `json:"artifacts,omitempty"`

	// Messages Log-messages that will be passed to the platform (default agent log).
	Messages *Messages `json:"messages,omitempty"`
	Metrics  *Metrics  `json:"metrics,omitempty"`
}

// ReadHttpMethod defines model for ReadHttpMethod.
type ReadHttpMethod string

// RestrictedEndpoint defines model for RestrictedEndpoint.
type RestrictedEndpoint struct {
	// Cidr A CIDR that is used to restrict the target selection to a specific network.
	Cidr string `json:"cidr"`

	// Name The name of the protected Endpoint. For reference/debugging purposes only.
	Name string `json:"name"`

	// PortMax The maximum port number that is allowed to be used for the Endpoint.
	PortMax int `json:"portMax"`

	// PortMin The minimum port number that is allowed to be used for the Endpoint.
	PortMin int `json:"portMin"`

	// Url The URL of the protected Endpoint.
	Url string `json:"url"`
}

// StartResult defines model for StartResult.
type StartResult struct {
	Artifacts *Artifacts `json:"artifacts,omitempty"`

	// Error An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
	Error *ActionKitError `json:"error,omitempty"`

	// Messages Log-messages that will be passed to the platform (default agent log).
	Messages *Messages `json:"messages,omitempty"`
	Metrics  *Metrics  `json:"metrics,omitempty"`

	// State Any kind of action specific state that will be passed to the next endpoints.
	State *ActionState `json:"state,omitempty"`
}

// StateOverTimeWidget A widget that shows a state of over time.
type StateOverTimeWidget struct {
	Identity StateOverTimeWidgetIdentityConfig `json:"identity"`
	Label    StateOverTimeWidgetLabelConfig    `json:"label"`
	State    StateOverTimeWidgetStateConfig    `json:"state"`
	Title    string                            `json:"title"`
	Tooltip  StateOverTimeWidgetTooltipConfig  `json:"tooltip"`
	Type     StateOverTimeWidgetType           `json:"type"`
	Url      *StateOverTimeWidgetUrlConfig     `json:"url,omitempty"`
	Value    *StateOverTimeWidgetValueConfig   `json:"value,omitempty"`
}

// StateOverTimeWidgetType defines model for StateOverTimeWidget.Type.
type StateOverTimeWidgetType string

// StateOverTimeWidgetIdentityConfig defines model for StateOverTimeWidgetIdentityConfig.
type StateOverTimeWidgetIdentityConfig struct {
	From string `json:"from"`
}

// StateOverTimeWidgetLabelConfig defines model for StateOverTimeWidgetLabelConfig.
type StateOverTimeWidgetLabelConfig struct {
	From string `json:"from"`
}

// StateOverTimeWidgetStateConfig defines model for StateOverTimeWidgetStateConfig.
type StateOverTimeWidgetStateConfig struct {
	From string `json:"from"`
}

// StateOverTimeWidgetTooltipConfig defines model for StateOverTimeWidgetTooltipConfig.
type StateOverTimeWidgetTooltipConfig struct {
	From string `json:"from"`
}

// StateOverTimeWidgetUrlConfig defines model for StateOverTimeWidgetUrlConfig.
type StateOverTimeWidgetUrlConfig struct {
	From *string `json:"from,omitempty"`
}

// StateOverTimeWidgetValueConfig defines model for StateOverTimeWidgetValueConfig.
type StateOverTimeWidgetValueConfig struct {
	// Hide Set to true to hide the metric value within the widget. This is useful when only the translated state information is relevant.
	Hide *bool `json:"hide,omitempty"`
}

// StatusResult defines model for StatusResult.
type StatusResult struct {
	Artifacts *Artifacts `json:"artifacts,omitempty"`

	// Completed the agent will continue to poll the status endpoint as long as completed is false
	Completed bool `json:"completed"`

	// Error An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
	Error *ActionKitError `json:"error,omitempty"`

	// Messages Log-messages that will be passed to the platform (default agent log).
	Messages *Messages `json:"messages,omitempty"`
	Metrics  *Metrics  `json:"metrics,omitempty"`

	// State Any kind of action specific state that will be passed to the next endpoints.
	State *ActionState `json:"state,omitempty"`
}

// StopResult defines model for StopResult.
type StopResult struct {
	Artifacts *Artifacts `json:"artifacts,omitempty"`

	// Error An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
	Error *ActionKitError `json:"error,omitempty"`

	// Messages Log-messages that will be passed to the platform (default agent log).
	Messages *Messages `json:"messages,omitempty"`
	Metrics  *Metrics  `json:"metrics,omitempty"`
}

// Target The target on which to act on as identified by a discovery.
type Target struct {
	// Attributes These attributes include detailed information about the target provided through the discovery. These attributes are typically used as additional parameters within the action implementation.
	Attributes map[string][]string `json:"attributes"`
	Name       string              `json:"name"`
}

// TargetSelection Used to specify various aspects of the target selection. If the action don't need a target selection, this field can be omitted.
type TargetSelection struct {
	// QuantityRestriction How many targets should be selected by the user. Values:
	//  * `exactly_one` - Exactly one target must be selected. The execution will fail if more than one target is selected.
	//  * `all` - All selected targets will be used. The ui will not show a percentage randomizer for the target selection.
	//  * `none` - Default. There are no restriction in place for the number of targets. The ui will show a percentage randomizer for the target selection.
	QuantityRestriction *TargetSelectionQuantityRestriction `json:"quantityRestriction,omitempty"`

	// SelectionTemplates Users that want to configure an action with a targetType need to define a target selection through the query UI or query language. Extensions can define selection templates to help users define such target selections.
	SelectionTemplates *TargetSelectionTemplates `json:"selectionTemplates,omitempty"`

	// TargetType What target type this action should be offered for. Matches the `id` field within `DescribeTargetTypeResponse` within DiscoveryKit.
	TargetType string `json:"targetType"`
}

// TargetSelectionQuantityRestriction How many targets should be selected by the user. Values:
//   - `exactly_one` - Exactly one target must be selected. The execution will fail if more than one target is selected.
//   - `all` - All selected targets will be used. The ui will not show a percentage randomizer for the target selection.
//   - `none` - Default. There are no restriction in place for the number of targets. The ui will show a percentage randomizer for the target selection.
type TargetSelectionQuantityRestriction string

// TargetSelectionTemplate defines model for TargetSelectionTemplate.
type TargetSelectionTemplate struct {
	// Description Longer target selection template description. For example, to explain the template's purpose.
	Description *string `json:"description,omitempty"`

	// Label Human-readable short label.
	Label string `json:"label"`

	// Query The target selection query is defined using Steadybit's query language. For example:
	//   aws.account="" AND aws.zone.id=""
	// For more information about the query language, please inspect Steadybit's documentation:
	//   https://docs.steadybit.com/use-steadybit/query-language
	Query string `json:"query"`
}

// TargetSelectionTemplates Users that want to configure an action with a targetType need to define a target selection through the query UI or query language. Extensions can define selection templates to help users define such target selections.
type TargetSelectionTemplates = []TargetSelectionTemplate

// TimeControl Actions can either be an instantaneous event, e.g., the restart of a host, or an activity spanning over an unspecified duration. For those actions having a duration, we differentiate between internally, e.g., waiting for a deployment to finish, and externally, e.g., waiting for a user-specified time to pass, controlled durations.
type TimeControl string

// TimestampSource Source of the timestamp. This is useful when the timestamp is retrieved from some other system. If not specified or equals `extension` the agent will adjust the timestamp with an offset calculated from the response date header and the platform's current time.
type TimestampSource string

// Widgets Widgets that will be rendered in the experiment result view after an experiment has finished.
type Widgets = []Widget

// ActionListResponse defines model for ActionListResponse.
type ActionListResponse struct {
	union json.RawMessage
}

// ActionStatusResponse defines model for ActionStatusResponse.
type ActionStatusResponse struct {
	union json.RawMessage
}

// DescribeActionResponse defines model for DescribeActionResponse.
type DescribeActionResponse struct {
	union json.RawMessage
}

// PrepareActionResponse defines model for PrepareActionResponse.
type PrepareActionResponse struct {
	union json.RawMessage
}

// QueryMetricsResponse defines model for QueryMetricsResponse.
type QueryMetricsResponse struct {
	union json.RawMessage
}

// StartActionResponse defines model for StartActionResponse.
type StartActionResponse struct {
	union json.RawMessage
}

// StopActionResponse defines model for StopActionResponse.
type StopActionResponse struct {
	union json.RawMessage
}

// ActionStatusRequestBody defines model for ActionStatusRequestBody.
type ActionStatusRequestBody struct {
	ExecutionId uuid.UUID `json:"executionId"`

	// State Any kind of action specific state that will be passed to the next endpoints.
	State ActionState `json:"state"`
}

// PrepareActionRequestBody defines model for PrepareActionRequestBody.
type PrepareActionRequestBody struct {
	// Config The action configuration. This contains the end-user configuration done for the action. Possible configuration parameters are defined through the action description.
	Config map[string]interface{} `json:"config"`

	// ExecutionContext The execution context contains information about the current execution of the action.
	ExecutionContext *ExecutionContext `json:"executionContext,omitempty"`
	ExecutionId      uuid.UUID         `json:"executionId"`

	// Target The target on which to act on as identified by a discovery.
	Target *Target `json:"target,omitempty"`
}

// QueryMetricsRequestBody defines model for QueryMetricsRequestBody.
type QueryMetricsRequestBody struct {
	// Config The metric query configuration. This contains the end-user configuration done for the action. Possible configuration parameters are defined through the action description.
	Config      map[string]interface{} `json:"config"`
	ExecutionId uuid.UUID              `json:"executionId"`

	// Target The target on which to act on as identified by a discovery.
	Target *Target `json:"target,omitempty"`

	// Timestamp For what timestamp the metric values should be retrieved.
	Timestamp time.Time `json:"timestamp"`
}

// StartActionRequestBody defines model for StartActionRequestBody.
type StartActionRequestBody struct {
	ExecutionId uuid.UUID `json:"executionId"`

	// State Any kind of action specific state that will be passed to the next endpoints.
	State ActionState `json:"state"`
}

// StopActionRequestBody defines model for StopActionRequestBody.
type StopActionRequestBody struct {
	ExecutionId uuid.UUID `json:"executionId"`

	// State Any kind of action specific state that will be passed to the next endpoints.
	State ActionState `json:"state"`
}

// AsActionList returns the union data inside the ActionListResponse as a ActionList
func (t ActionListResponse) AsActionList() (ActionList, error) {
	var body ActionList
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionList overwrites any union data inside the ActionListResponse as the provided ActionList
func (t *ActionListResponse) FromActionList(v ActionList) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionList performs a merge with any union data inside the ActionListResponse, using the provided ActionList
func (t *ActionListResponse) MergeActionList(v ActionList) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the ActionListResponse as a ActionKitError
func (t ActionListResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the ActionListResponse as the provided ActionKitError
func (t *ActionListResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the ActionListResponse, using the provided ActionKitError
func (t *ActionListResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ActionListResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ActionListResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStatusResult returns the union data inside the ActionStatusResponse as a StatusResult
func (t ActionStatusResponse) AsStatusResult() (StatusResult, error) {
	var body StatusResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStatusResult overwrites any union data inside the ActionStatusResponse as the provided StatusResult
func (t *ActionStatusResponse) FromStatusResult(v StatusResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStatusResult performs a merge with any union data inside the ActionStatusResponse, using the provided StatusResult
func (t *ActionStatusResponse) MergeStatusResult(v StatusResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the ActionStatusResponse as a ActionKitError
func (t ActionStatusResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the ActionStatusResponse as the provided ActionKitError
func (t *ActionStatusResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the ActionStatusResponse, using the provided ActionKitError
func (t *ActionStatusResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ActionStatusResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ActionStatusResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsActionDescription returns the union data inside the DescribeActionResponse as a ActionDescription
func (t DescribeActionResponse) AsActionDescription() (ActionDescription, error) {
	var body ActionDescription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionDescription overwrites any union data inside the DescribeActionResponse as the provided ActionDescription
func (t *DescribeActionResponse) FromActionDescription(v ActionDescription) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionDescription performs a merge with any union data inside the DescribeActionResponse, using the provided ActionDescription
func (t *DescribeActionResponse) MergeActionDescription(v ActionDescription) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the DescribeActionResponse as a ActionKitError
func (t DescribeActionResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the DescribeActionResponse as the provided ActionKitError
func (t *DescribeActionResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the DescribeActionResponse, using the provided ActionKitError
func (t *DescribeActionResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DescribeActionResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DescribeActionResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPrepareResult returns the union data inside the PrepareActionResponse as a PrepareResult
func (t PrepareActionResponse) AsPrepareResult() (PrepareResult, error) {
	var body PrepareResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPrepareResult overwrites any union data inside the PrepareActionResponse as the provided PrepareResult
func (t *PrepareActionResponse) FromPrepareResult(v PrepareResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePrepareResult performs a merge with any union data inside the PrepareActionResponse, using the provided PrepareResult
func (t *PrepareActionResponse) MergePrepareResult(v PrepareResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the PrepareActionResponse as a ActionKitError
func (t PrepareActionResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the PrepareActionResponse as the provided ActionKitError
func (t *PrepareActionResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the PrepareActionResponse, using the provided ActionKitError
func (t *PrepareActionResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PrepareActionResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PrepareActionResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsQueryMetricsResult returns the union data inside the QueryMetricsResponse as a QueryMetricsResult
func (t QueryMetricsResponse) AsQueryMetricsResult() (QueryMetricsResult, error) {
	var body QueryMetricsResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQueryMetricsResult overwrites any union data inside the QueryMetricsResponse as the provided QueryMetricsResult
func (t *QueryMetricsResponse) FromQueryMetricsResult(v QueryMetricsResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQueryMetricsResult performs a merge with any union data inside the QueryMetricsResponse, using the provided QueryMetricsResult
func (t *QueryMetricsResponse) MergeQueryMetricsResult(v QueryMetricsResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the QueryMetricsResponse as a ActionKitError
func (t QueryMetricsResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the QueryMetricsResponse as the provided ActionKitError
func (t *QueryMetricsResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the QueryMetricsResponse, using the provided ActionKitError
func (t *QueryMetricsResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t QueryMetricsResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *QueryMetricsResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStartResult returns the union data inside the StartActionResponse as a StartResult
func (t StartActionResponse) AsStartResult() (StartResult, error) {
	var body StartResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStartResult overwrites any union data inside the StartActionResponse as the provided StartResult
func (t *StartActionResponse) FromStartResult(v StartResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStartResult performs a merge with any union data inside the StartActionResponse, using the provided StartResult
func (t *StartActionResponse) MergeStartResult(v StartResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the StartActionResponse as a ActionKitError
func (t StartActionResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the StartActionResponse as the provided ActionKitError
func (t *StartActionResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the StartActionResponse, using the provided ActionKitError
func (t *StartActionResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StartActionResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StartActionResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStopResult returns the union data inside the StopActionResponse as a StopResult
func (t StopActionResponse) AsStopResult() (StopResult, error) {
	var body StopResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStopResult overwrites any union data inside the StopActionResponse as the provided StopResult
func (t *StopActionResponse) FromStopResult(v StopResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStopResult performs a merge with any union data inside the StopActionResponse, using the provided StopResult
func (t *StopActionResponse) MergeStopResult(v StopResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsActionKitError returns the union data inside the StopActionResponse as a ActionKitError
func (t StopActionResponse) AsActionKitError() (ActionKitError, error) {
	var body ActionKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromActionKitError overwrites any union data inside the StopActionResponse as the provided ActionKitError
func (t *StopActionResponse) FromActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeActionKitError performs a merge with any union data inside the StopActionResponse, using the provided ActionKitError
func (t *StopActionResponse) MergeActionKitError(v ActionKitError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StopActionResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StopActionResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9jXPctrH4v4LhrzO28zudnKRJW8286aiR3GhiN362/DKdWE/CkXtH1CTAAKBOl0T/",
	"+5tdACRI4j6UWP14r51prSNBYLFY7Pduf8pyVTdKgrQmO/kp0/BDC8b+SRUC6MFpboWSby23rXnTvdzg",
	"q1xJC9Lin7xpKpFzHHr8N6MkPjN5CTXHvxqtGtDWzwh3kLc48qLAn0ula26zk8xYLeQqm2V200D8++5o",
	"pY78w7YVxfzdu4uz+PmRqBulCZCG2zI7yVbClu1inqv6eKXUqoJj/DC7v59lxnILOPQ3GpbZSfb/jnsM",
	"HDuYzXG/a6CPEC1CQ5GdfD+AP0x31UGtFn+D3Gb3+FUBJteiwbHZSXZZAvv68vI18zhmDd9Uihes4cZA",
	"waxitgTGaWlmCOMMZNEoIa2ZI2KErXANBx1zh8L8qWT3s+y1hoZrcO8/zmnlSi7Fir4qCoGf8Op1NMLq",
	"FlI79dtwn7eaFpuzy1IYfGa5kIa2C7I4ag3o4UhWKAlsqXSEkjl7rYwRiwpGYxuueQ0WtGFcAytgKSTi",
	"s9SqXZUxUiMw59nkyGb90X6FyLqz+8jkfDw+nuMfQ96W6xXsBfzSjdpN2v7oPz5tN45M08TtaZh5Io+o",
	"+z9b0JtXYLXIzccm7ul2alqI/YCL/quS8b8CCeLJ12Asr5vpQbxQmq1Lblk3hvDgz+aWVy0YZkrVVgVb",
	"ANP4HG6hQLR02y64hSOcYLLz3fTfw/UYd2FAX/1NYK/ayoqmgvAmgGRYyZsGJJET3OI7Tw7dkPga0WVh",
	"/rbEt+it5dp+TAnxb3m+85wN4rs7qhTHoxNJ8Lu3VjX/Pqi/40GpZs85qWZyTASjaZQ0sb78Uhj7xj9+",
	"0Ilxufl2mZ18fwiWcJHsfnbI0G+EPdda6ez+KoGgAOlIUrFKGNuhYqp/4vqs2+X9bGQrPNruuwXa6pH2",
	"n7yzOxTwHgVnNPGiU8EfmQTOon08CiYKv58dyAhb7q9Gj46RQfJo2PDrPCZNDHRXvg0ZE+21x8VQfX00",
	"VIyWeTR8JPWXbQpIjIeBAvKYTELbfySPGEn1eP+9WH/E7avmcXc/FZZbRWXYOyoBbtFeUsYcbKL+v9bq",
	"VhRgWAGWi8owvlCtZZw1wYRyIMwYzFfzmTMVhlaVapzyLCwruZmxUq1R4DcaDEiLj63qrDfDuCzCEKvF",
	"agUD0y2bjVSq3ifyouIrM93BaTeALXEEswgicojWqx4BXIi5DKLZNJCLpchZzg2Yk/eSsU/YzdnF29M/",
	"vTy//vr89M3ln85PL2/YETsThiM2cIYSuLYL4JYtwK4BJOMr3CnurKm4RbXPH6MwnUXZosrXWxLZLBMW",
	"aqc2yrZG9WuycqR8BXuqe8C15hv8nXMLK6U3U9S8QwQgIH6I+NGf2DLGxFrYUkhGtrWQFvSS52DmWWLp",
	"YhcpRXTmLKjuyK1iJVRkWNaslQVoYxFZzu7sIRGGFUrIVXLtUkh7mG77NY68n2UiT4F5Khm+cGQiTEcl",
	"ogBpxXLDNqrVHUSS4GvFnP0FoKCtoKhmBbf8qNUi+CjwbLlkouYrQPBrfvcS5Ao19k+f039mqMBb0AjD",
	"f+PnJ/NPfpPaqCgSQDMLeSlFzit2cTaBvZXihxaqTb8JIj2cGg87uEX+qlq2FlWFL3CqasPWXNL9bA0w",
	"o2pAUlixSnwAdqP0ag53vG4qmNeboyWX+eaIW8vzDzfJI/ogZHHYEX2DI+9nWcUXUKW2W7Y1l0caeEHX",
	"jsaN3TwpEJzMNPug8ELzq5iR4ee9hyjBKnvv0UEsZs4uSzAQe50I+eRFwUsARU9fxDzC61teiYJb52Tp",
	"uMR+rHYQTtjELHMkcuEms7oF3K1TpfYiq7XcCrk691LoDSxBg8xJ1pKQ/rUz2Nb84im+E7b8ilfVBbKu",
	"W165KVXzq2ByDra3UEEemN1+T1s/fDrDJdQoGrxMq6oDFIzLbTPcXyEnbjQgWy/SAYKz7v0J3e2b0Wxz",
	"M5n3hglpLPBi3sN/SUT0069frp8uWiYl3EQNXylptar2Ij0aej/LbkGbpFy6LIH5l0PJN2dvoIZ6gRqI",
	"YkLmGrhxN5j8ns4HiBChTGBtg3fS22xLIUnrMHTLe7FPV1ispNLAuNxEI1lecrkCQ/LWaXi87kSfB3DO",
	"vgNWKKYhV3UNsmCt4Sti4gbqW9DMoSotnteiWIHde5W+88PG3h9RZIEj9+gcnrTn8cNzGrDNnqsE3nA1",
	"serPBjNOnOuRFJ8cJj41A9bbOA2W9YoiE9J53nAt73pCRYSOakMfJxjwugTZDWUu+kA8HQXiLg01siuS",
	"QbqWVwyVF2bhzrKnOZdBaWA11x8KtZbP5uw7z/sLYZqKb3rQGq2KNrfs3YUDcTtYWzTFMVhhJULgdBGr",
	"AgxO2UXIhUSVRyyJQ6L+XyntJZYtB69QtUJYgkqLn1/jeWROg7tec43KUkKzHVEjvZ112L3qCOMbr2Wk",
	"tM8F3i8Uzkimverj1CFhfFwp0pxIL3VaaqSY4n/zihvjVCnkB1qo1jDdSsl7qyjSBBq0RXFByeCuAS1q",
	"kDbGhFOccEcl0L+V4sW1BYNWnbIl6KS2P7IdU+osyJLLHIqYy7158RX73e+f/4691mpRQc3OvH2HOhS5",
	"ak9fXyCN100lUAcMLla2UMXG6e+4IDM5SNy8mdC9sxgPUN7grqm4dNexM7noXgrDVJ63muRuYM6NgzhJ",
	"0Sg6cK+pVd+9uWA6CHGvIjt1WIALIXaLP2zRXkEpYMnR4D/JCDlQZGNB+AlbclFBwY5YFKMvORnYkFso",
	"SM2mUa0GM3Oodlo24/ScbjYYy9alyEv6eIFWpsAxSFZQsMVmrGn25py73qgDNVDMmFg6TPt8B2GYBttq",
	"2c8yyoSYs0+Y35/bhga25obxyAhxxLEuBZ0v2bRDftQxNORxUDCOy/b8xsvLjw15dN/cOeADf1RJW9oJ",
	"pikxmVJpOxtTsmnrmuvNiGjIznoAAz6EVPdMPeaVtI1I0HpH0ywKlkzhwKeG8aoacrP4fI6dZyOn8K87",
	"Z0j4aNzn+OdB1orn1VuV732Wy2j3YfmrZPxku4bRm0uTQB7Pc2gsFC9EBai0JszBdwQWW+INIEPbcxcU",
	"JUW3Qe/j8IY4DnbaS1iArn9kISJl4eAnOPTJwP7b7QhKW3i8uCXRkNACSkCZ4y5YB0AU6W8qjjKFpKJL",
	"wLhruHT3IEzLDAx8SL36FPxIEe0ulKqAS+dHIj76X6hlp+6Hf+/V8M6V1oHp5bh7vR7oM8seiEKBYVJZ",
	"fzIbxrdPmPZ29UbPNvQpTSuMsCiQBMLHc9ZbRylnQCmKAiRbalUnEDhV+jiTsGbGQjNn53fCEOfFn35K",
	"Y/3EzmHpfDtFCoQ5O02+CFSAOyNvhbtrTCrNSn5L/q/oBLedsZtYKPkKDFoxqZOu3SvHeToBUKr1QHPv",
	"lHOnvW9RgUPSEIIeS1Uh86pFC8Gr4Q4jnGkgGg+K2mN7O+MQ1066e7in89e40fYAU/O7LdeUUriEFHVb",
	"77io38pqw3y8BUHYwu9ukOBXoG9I975pQOcgLV9B7Gn0YwgsIf8ZwZK83gLSB9h4Xuq0utQBMNJ1UFnx",
	"tIwfob1okfwXCGXrja7ObnPBUJ938SRYrWwpoEp7WHy4Zgrlt403n0NAJ9DJjfv4Zhb++v7K48P9vCYJ",
	"dBPtAxc1c/Yd7VRTkAw1P9OuVmD6ybs7c7CfsxPZ3zado22/FFS6gITp9FfVEnZdHqAjEcIb3WH6yCG5",
	"p4u0jCMltlJrP56obuat51UZZlFGjCz1iHB6fWaPpOn5jARnwj5IukUMeot3ILae3YRT4ZbzxhL7dVt3",
	"6k/w9TEhl1WLypxTZW8cSd6EZCBuOmOZXneZBUTCN3N2YRmvjPKEQ0gXdaPVLaojBvRRLxzBGUQmVvy7",
	"5KpArN2f14FIAuJnHT5mWX+30agLMYFZhopYNss+wOaa0IE0pivEKNxZroHj9C5jQeGMJfDCTS2s5tb5",
	"wTQYI1dHa6U/gDb7nR/BC0f8xA++GuT/wMMSxk/lZuwT6axhyvMaSuBh3paEO7s3Tx6Sira2YsnzhPFx",
	"6k2Omm9YXiplYODM898Z9pRrQqTeOO35We9yqTiSI2rSPlS92HhXDqkLQuIOrYu6Bo9MH4ANEe9ObaiB",
	"SK3ksthQyPquQagoj43McQ2N0tZFsI2oRcU1xQGnBhE+nW55wQ18+VsGMlcFFPTpMFL45R9+9/nzz58n",
	"mPYWAf/1TvHucUg+5d6h7FzdpBAtnfVuQRo6i0iw9FNxtgCLiKar5zBJZishuVBriRjyqpiJji6kDHR+",
	"rmt3oeeW6/nqx1GU9LMvvjz0UhDiYmMvENkOAjzcOO1mu5+uYLJp+H2XMTs9sMvL191NijSBtxZ4sVkI",
	"m7a88exaKVBNp0OaUlwNtlR7g69vgBdfW9u8cqMp4InIn1zOhVFVa5EP2DIw6gHsBEEfzz5OxrJH50dr",
	"zQKo0QHSzAF7bOALOE/Ui0yVq/5S525YXzoQxwJcbgvuxbn/Ym4wjAxNXRx4Gqdrc5rnqpX2okgDcvrd",
	"W2RIOIRdnHWT0lGGoH3aXRYc0woVUwO2j0f0yRHeAVMw3IuMF0sperTqa7EF0kYr5JsPgzKpuoySnned",
	"Tr/Y5AD2zP1Oi32Tv3tzccjsPYJ6qfANbLbN3gkO1MX99NHTgC6/YrVhC+jzfKDYs/CObXVLRPv6tQtr",
	"wL9zC0W4bQk7oHs1SnMILmcik6cwX7nEhyFnisVJnA/1LGRDfKWkBC/7TcmrKngZ+HLp/OOLTeePPGYu",
	"anK4gfBmssNpytR9Qk6c36EpKOzYwNhqNJALgWI99N3xUtwNXCiqdw1w9kGqtWTHjGLBQNdbLTs7i9As",
	"4Ra0jxFP2c/DDPzI/ehiLM3WO3C73Yjunf3ez0bSKq0heh41Vu2D5u/wvN+P3QWfCSpUeF+qlQtXpzbv",
	"4t0Of6ZUa8MqtQouJZPAolqFhIY4P+uz3++KDOwf6acM9keu6rkJ8nzuYJxX6vCQZwBzNvXr9+hI0PBW",
	"N9tLtTpKOtqGh9glMTwN/ld31yu1ejZFprOU9yda0bIv3GDUZOE2UHKIpfnwcMBfAYt2RUYaPV5zLUMU",
	"JxnDqfttJ9NJusK3Q8rVok/eqlbncEgWSjx8YFiHHZ7++fwvl3upP2wkOu9wpNtP+0V3DGlj8Kc9fs2d",
	"lmHwhsQ0M06d6KjGKlVZ0eA8AzIdboV5gLfvyOwkYPNrKPggERJwfj+BPaX+u0zCKcihLhBlxQK8MRkL",
	"tyAQ62hg8PPhJdF85cYPPMveqGVmYyzUbAElvxU+GcMqz+kps5MvlLZpy9eFFEC7HBS/Psp5tTCgbyn0",
	"Oof5bAAbzy3y96eOtTmnwTNGyQwmaY94tPxCsvwGNsdO7jRcDENqfW2EV5vJ/yQMq1UBFRSML1ECv9aU",
	"zwqteUK2tns93JoTmMalxtZ8443zuPxCUpaWYTfX1/jn9fVNZ/xbRZns/UIu5CRssmY47Rt+1a/ioCBc",
	"V2hYcStuoToQpsh294P8gWzmO7lcQvZ3hcARznmwVmvl1c+QJLfmpqObQ4uCPwaX7TQXP7ds6wX53eKa",
	"ymWluP3yt4mAeV947Em10zria+/fJFhVl2Z8IE+hme7Hc2/nKKPc5EmEmqqCDkxzpkKhUa7zFBQ2HLF9",
	"14npppWwQfv+mGm9w+zsR0uMHhfF9sU3EQBXU/y5eqz9WNyaePzP5i4KkP5ruYwOJ6mDU7F35YpPOl6M",
	"VhihybqMkCVF7GS+CbH2kM3U9+xARQAng+KP7JJ/AMNCVKKLQzlei9i++fT589rcMKXxT3MzQvb798X/",
	"fyrNz7X52fxc/1z+XDxLI39ErVezx6PIBxxlRICRofX627eoVL9+h/97dv7y/PI8aSAkbPrDSvy2OQX2",
	"1fuNxpsXWtUuIf7UWi0WrYXs/moKWXJgMmnC8uBgIG1Yg6+2c+lcLtme8TBHaOMRIgMfYJNuftJ90IWP",
	"R17Q7VBdjtfERSinpSeSrqZw7CZx2ueK2xIti/1+gh6OK1cC7XezzVUwSNHvXMM8OGJKyvfVqDYWrOlm",
	"8/6FECEK3gZUNnlVqbUJqSRKhjzSeoqzZgSd85J+HK9CP/fBzoUEOFeD4uohKhPya1gJPk2diyMuhwRa",
	"yC0AIbv5IXW0ne1/qE1nHl4iln2MvhrbOmlMStY/Ikb/HqjBfY5iShHJ/vk8XcCa8NFO+0aJIpXszr66",
	"OHszKX8Mbm1iMp759ekIVuFNDy4NCXat9IeRfHz6/fOjP1z99Ons8/v37+fPfvr8vn/w9Dj8/dn9sz8m",
	"Sza3p/2QpdanC/sU8PMu0/qF0n0m8DG5vlZobzWtbpQBFw9KWnCN0vYVv9uSAMXvKAEKBzFnGXVYI97l",
	"EBeyJoNgOI9UNT9FdvLlF198/gVlXLnfz1OBGoJGyN3pWH83aFpdpSF59+bljtPYK3d8OobL/yAS7Xfe",
	"n0jqnsfNEv7NMrewzBTWLHx7Cxrt/4fEAbjXpdWSqVukNlEnoiou597uNaMTYFz4T521N0jReOBML/G7",
	"fpqDEJeYhh710zwgfOHctr9gyUv3ZbToIToLbfAaT+WanEMpCeHv7wPheacjPHbuoQdOQlmlYZq0CuVw",
	"O+vJp6+aDMiMm2f13UomtHwYyY9obcI+UMtOeFRHwNOo3fCMFjoMuph+Hw+0eJXD4IovxOPBFa9yGFzD",
	"W/N4kA3XOQy2/gY9AK4dMPTzHbZ+fPkmEJSiSChZb8G6VjItJRDioEkDy9g57rlQXAi6bCsXEqHcG9Ih",
	"NZemoqIIJ0fiLCIqQ6vglg80hi6xdjdG4h1uwUn7kQ0BqvGEZBVLn89B8TS0jIV0iGxUVaVK7Bg3rFJy",
	"hf92MyNOlrwykEw0/t9t2/XovfKtp/7PqHmIisuuFW0ig8SZYhRxJB+QoiiiSxTpCh5dUJQVwuSoFWx2",
	"uJ12xrkPLJRLNa80ke/LdOmxLkGYIt2pHEK/O5+yPPSk9Zthk+m5hqgBT+tT4qP2BYMasY5xhTTAUATM",
	"tzYnDtboQbZMhNuU3XI5bYSS6DEVVSGESnlOcWoTrK2xVT5nF4MmVIWST6wraeCTwbOoNiME1FUtrE9z",
	"GwfGOCkxwcuQhPprtWY1lxu/VNzh2K3a57u5zhHEt80Jey/ZJ+wG7nhuq821knDDjti5+0l+QA973Rob",
	"z+YKJaIQPPLbJRcVE0tWK2ocxGU8gzD9x25VXlW42mlV9UAG+OMiSLdWK9xDKoAs1Zpx1pc4MM1loWrx",
	"I+jO3J4ckVtV+k2euYyKuS8IRyqWvevFN8uigrpuRm/qIwk4MIeQ/TKookyh6BiQkiuqmMAfKZvCJFvx",
	"/LIGPNP2OJMSGg83eYvjPnA9oSnqmUHujjl7xW1ehoIZUdx4Yvf3/yZ0t7jslg09/7rI/1lgOd+IAzwZ",
	"EfyRGjm+7fsZQkDKVNrtrJ58qSQ1/pv46vx0gwbs5CTzxZwzX5lRcc8WwxdPTPCZTdqvffbbX1xRQW0A",
	"XJLIeNqkMd1F5bcKw36vrq8nlQq7cENrhFz1kbQnxg+puFy1fAUDRFC3Qr42c58B/h/vs/cZO/3LGT38",
	"UUmYi4Ievpf4GfGYtCAbrjJjTUV9kEKqUQxQofK2Ez4EQmltY06OjwuVm8jYz1V93Bo46p4c0ypHYZX3",
	"8oBT2pId6pC8nWw7mjycfE1SsIVOb6FJXt/lzeVDhcr3TmThferq8nxZIU9QeaQpOOS/u2BKT477vM+l",
	"juoUp7fFjDrZhIEt6lyjxQ9Ppd6G1fu9iE9ltVwOG3uli8FwlyCo3HFBSHb9XiyXgDoF3IK0oawIkYfS",
	"J/TdYaUydsYoF44O51bYDTMNl9SckdyAXLJWhj4NRRdPdxfLlsr0jX1KfuuK7cOgGVtD3+hIIJMK7T+p",
	"HpGy7ro2qVxQ7YRL/y6gqdTG5U0pSgI35YxS9uBu95dUc9UDTL3I0DjjxszIXNOqqqKdDAohB8jzVY+4",
	"GA7x6yYl5eU0N2tkc9PzTrULw9NG9WCI7+Hi/i8kXHiY2uFQ/yOf1EiqYd+2AfeNbO+HllcGVS9/J27Y",
	"yHrlxd9Q6Rqu566nRGFrwLKcV3nrDPuu30LX+Yjau7nyTRYK9kPU+ElXadH5knstxEO0D6+9A/vwLuxj",
	"j+G+1IM+83ZvksI41HsfcdRujuy7vqfcuI0YvdidHByln/oy8FsBa5+gOWiVRW2O3NV4QN/LHs4h5FMO",
	"dE+eEGnaGpn999MW0Fc+4/zkp6wSOfim0Z2VqrOT7NXFZajJdT8Gvp6QANPZ4uz09UXUSe8k+3T+fP7c",
	"1eCD5I3ITrLP55/On7tYZGmyE9lWFRk0RZtvg/P+fwIAAP//NpHMtVJsAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
