apiVersion: v1
kind: Namespace
metadata:
  name: example-nodejs-logging-attack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-nodejs-logging-attack
  namespace: example-nodejs-logging-attack
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nodejs-logging-attack
  namespace: example-nodejs-logging-attack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example-nodejs-logging-attack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-nodejs-logging-attack
    spec:
      containers:
        - image: ghcr.io/steadybit/example-nodejs-logging-attack:main
          imagePullPolicy: Always
          name: example-nodejs-logging-attack
      serviceAccountName: example-nodejs-logging-attack
---
apiVersion: v1
kind: Service
metadata:
  name: example-nodejs-logging-attack
  namespace: example-nodejs-logging-attack
spec:
  selector:
    app.kubernetes.io/name: example-nodejs-logging-attack
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
