apiVersion: v1
kind: Namespace
metadata:
  name: example-go-kubectl-attack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-go-kubectl-attack
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-go-kubectl-attack
  namespace: example-go-kubectl-attack
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: example-go-kubectl-attack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: example-go-kubectl-attack
subjects:
  - kind: ServiceAccount
    name: example-go-kubectl-attack
    namespace: example-go-kubectl-attack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-go-kubectl-attack
  namespace: example-go-kubectl-attack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example-go-kubectl-attack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-go-kubectl-attack
    spec:
      containers:
        - image: ghcr.io/steadybit/example-go-kubectl-attack:main
          imagePullPolicy: Always
          name: example-go-kubectl-attack
      serviceAccountName: example-go-kubectl-attack
---
apiVersion: v1
kind: Service
metadata:
  name: example-go-kubectl-attack
  namespace: example-go-kubectl-attack
spec:
  selector:
    app.kubernetes.io/name: example-go-kubectl-attack
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
