apiVersion: v1
kind: Namespace
metadata:
  name: steadybit-extension
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-go-kubectl
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-go-kubectl
  namespace: steadybit-extension
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: example-go-kubectl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: example-go-kubectl
subjects:
  - kind: ServiceAccount
    name: example-go-kubectl
    namespace: steadybit-extension
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-go-kubectl
  namespace: steadybit-extension
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example-go-kubectl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-go-kubectl
    spec:
      containers:
        - image: ghcr.io/steadybit/example-go-kubectl:main
          imagePullPolicy: Always
          name: example-go-kubectl
      serviceAccountName: example-go-kubectl
---
apiVersion: v1
kind: Service
metadata:
  name: example-go-kubectl
  namespace: steadybit-extension
spec:
  selector:
    app.kubernetes.io/name: example-go-kubectl
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
